### ISSUE TITLE
Would you be open to features allowing WordPress to administer LDAP users?

### ISSUE THREAD

**Issue by meitar** [heiglandreas/authLdap#101]
Hi,

First, thank you so much for the plugin. I am currently working on a project that requires LDAP integration and am experimenting with using your plugin as part of the solution for my project.

My project is unusual in that one of its requirements is to make the WordPress user admin screens the sole interface for network administrators to manage user accounts. Since many other services can authenticate against LDAP but not necessarily WordPress, we are looking into using LDAP as a back end but *without* requiring a separate LDAP browser, nor complicating the user experience admins already familiar with WordPress expect to see.

As I was looking into your plugin I saw [functions such as this one](https://github.com/heiglandreas/authLdap/blob/bc63c4ee422647bb79d57d18fae925299b814ec3/authLdap.php#L554-L578) that hide portions of the WP admin interface for LDAP accounts. This is the reverse of what we are wanting to do.

Hence, my question: would you be willing and/or interested in adding opt-in features to reverse this situation? I.e., would you be willing to merge in pull requests that make WordPress's user UI screens the place where relevant LDAP properties like a user's password, etc., are stored?

This would of course only be an opt-in feature and even can be disabled by default. (Our project can automatically customize the settings of a plugin during deployment.) It would be great to use your plugin for the heavy lifting of our project, but this requirement is a deal-breaker for us, and I would rather not have to maintain a separate fork of your plugin if I don't have to. :)

Thanks again for the work you've done on this and for making it free to the community!

**Comment by heiglandreas** [comment]
Hi @meitar.

Thanks for the kind words! 

The main purpose of this plugin is to authenticate users against an LDAP-Server. It also allows authorization using information from that LDAP-Server but strictly speaking that's not really the scope of this plugin.

Editing LDAP-Informations on the other side is clearly our of the scope of this plugin. It would be possible to create a further plugin that would allow user-management in an LDAP via a Wordpress-Backend. There are already a few applications written in PHP that do such stuff (GOsa, PHPMyLdap) but they are not implemented as a wordpress-plugin. And as administering an LDAP is a rather complex task such an implementation is a very tedious and lengthy labour. 

So I'm really sorry to say that, but I will not be accepting PullRequests against this plugin that enable Adminstration of an LDAP-Server. But feel free to start a new plugin that allows the Wordpress-Users to edit Informations in an LDAP-Server. 

Cheers

**Comment by meitar** [comment]
@heiglandreas No need to apologize, I appreciate your taking the time to answer my question. :) I understand that the process of LDAP administration is complex and somewhat laborious, so I don't begrudge you for not wanting to include it here. Again, thank you for the great plugin and answering my question so promptly.

**Comment by meitar** [comment]
Hi again, I just want to leave a note for anyone who might have stumbled across this old posting that I've started a project to implement the above as I described it. It is called [WP-LDAP and is available on my GitHub account](https://github.com/meitar/wp-ldap/). :) Thanks again for `authLdap`, it is a great inspiration!
