### ISSUE TITLE
nickname and display name explicitly unset on update

### ISSUE THREAD

**Issue by gramakri** [heiglandreas/authLdap#103]
These are unset in https://github.com/heiglandreas/authLdap/blob/master/authLdap.php#L354.

Is this because the user might have explicitly set them to something else (and this plugin does not want to override that) ?

**Comment by heiglandreas** [comment]
That's exactly what it does. The user can set the display name and doesn't want it to be overriden on each login. And the same applies to the nickname the user can alter in the backend. 

There would have been different solutions to solve that but that was the easiest.
