### ISSUE TITLE
Missing parameter in add_filter in authLdap.php v1.4.10

### ISSUE THREAD

**Issue by jmussman** [heiglandreas/authLdap#104]
I am successfully using version 1.4.10 with wordpress 4.5.10 and 4.5. This is the current version that is installed through the wordpress dashboard.

However, turning off the password fields for LDAP users does not work. I traced the issue to the the show_password_fields filter not receiving the user profile. That happens because the registration of the filter at the end of the file as "add_filter('show_password_fields', 'authLdap_show_password_fields');" is defaulting for both the priority and for the accepted_args value of 1. The fix is to change the line to "add_filter('show_password_fields', 'authLdap_show_password_fields', 10, 2);"

I realize from posts last fall that this file has had changes to include the allow_password_reset filter, which does have the correct registration. If this has already been fixed but not published to the plugin repository my apologies.

**Comment by heiglandreas** [comment]
I'm the one to apologize! You are right. I did not push the changes from github into the Wordpress-Plugin repository! Await an update within the next days!

Thank you for mentioning and sorry for the inconvenience!

**Comment by heiglandreas** [comment]
This should now be fixed with the current release of authLdap v1.4.14

**Comment by jmussman** [comment]
Thanks Andreas!

Joel
