### ISSUE TITLE
Typo in AuthLDAP version1.4.20 

### ISSUE THREAD

**Issue by klb248** [heiglandreas/authLdap#116]
There's a typo in ldap.php file of the 1.4.20 version of AuthLDAP on lines 106 and 107.  $this->port should be $this->_port.

Also please put older versions of the plugin on the plugin's wordpress.org/plugins Developer page.  If that would have been available I could have quickly rolled back to the prior version and my site's login downtime would have been minutes instead of hours.

Thanks,
Keith

**Comment by heiglandreas** [comment]
Sorry about that Keith!

I'll as quickly as possible add the older versions. You can also download them from the github-site as they are there as tags as well (https://github.com/heiglandreas/authLdap/tags).

And I'll add a fix to that as well along with a test to make sure that doesn't happen again!

Thanks for reporting and again sorry for the inconvenience!
