### ISSUE TITLE
Add support for LDAP servers which have anonymous binds disabled

### ISSUE THREAD

**Issue by ziermmar** [heiglandreas/authLdap#119]
Let the user specify an account used to query the LDAP server

**Comment by ziermmar** [comment]
Well, I'm sorry, I'm really blind. This feature is already included.

**Comment by heiglandreas** [comment]
:smile: 

Suggestions on how to improve the docs that it's easier to find?

**Comment by ziermmar** [comment]
Well, just minutes before going over wordpress I was configuring LDAP for pfSense, which has an extra textbox for an auth dn. I kinda was looking for the same thing in authLdap and somehow must have completely overlooked the description of LDAP Uri because I was looking for keywords like 'anonymous' or 'authenticated' or something along those lines. After that I tried CTRL+F in the Readme.md for those keywords, again finding nothing... So maybe an improvement would be to extend the description of "LDAP Uri" in Readme.md, specifically mentioning how to specify a dn for auth using some of those keywords?

I know, it's oddly specific ;-)

**Comment by heiglandreas** [comment]
No, it's not. Thanks for the description. Anything that makes it easier to use is welcome!

Would you want to open a PR? Otherwise I might add something and try not to forget to quote you so you can give me feedback.

**Comment by ziermmar** [comment]
Sure! I'll put it on my todo list
