### ISSUE TITLE
Double quotes in password not working

### ISSUE THREAD

**Issue by scrobbleme** [heiglandreas/authLdap#123]
double quotes: " are still not working as part of passwords.
This is a follow up to #108

As a workaround it still works to add stripslashes in ldap.php#authenticate:

```
 $dn = $res[0]['dn'];
        if ($username && $password) {
            $password = stripslashes_deep($password);
            if (@ldap_bind($this->_ch, $dn, $password)) {
                return true;
            }
        }
```

**Comment by heiglandreas** [comment]
Thanks for mentioning!

It has been fixed with c3dbc9d
