### ISSUE TITLE
Add an information whether the LDAP-Extension is available.

### ISSUE THREAD

**Issue by heiglandreas** [heiglandreas/authLdap#125]
So a less experienced user sees right away that the plugin will not work

**Comment by paolofarina** [comment]
Hi Andreas, good idea! 
i've seen another plugin who make this. I paste a printscreen of its alert! it helped a lot my noob experience!
Bye! 
and thank you for your help!


![ldap alert](https://cloud.githubusercontent.com/assets/19834327/26443771/0ffe0e20-413a-11e7-9a17-9ccc77e5372c.png)
