### ISSUE TITLE
LDAPS protocol support

### ISSUE THREAD

**Issue by Olga-Li** [heiglandreas/authLdap#127]
Hello! 
Can I use LDAPS protocol with your plugin?
In LDAP URI according to RFC 1738 value format
ldap://uid=adminuser,dc=example,c=com:secret@ldap.example.com/dc=basePath,dc=example,c=com

how can I use something like
ldaps://uid=adminuser,dc=example,c=com:secret@ldap.example.com:636/dc=basePath,dc=example,c=com

or

what should I do to connect with LDAPS protocol? 

Thank You.

**Comment by heiglandreas** [comment]
LDAPS should be possible to use with this plugin. The second LDAP-URI you posted should work. 

*But*: LDAPS-setup can be a bit nasty especially when you are using self-signed certificates. I don't have a perfect solution and personally think that the ```TLS_REQCERT never``` you often find (f.e. [here](https://qadrio.wordpress.com/2012/03/14/ldap-ssl-connectionbind-with-self-signed-certificate-using-xamppwamp-on-windows/) or [here](https://stackoverflow.com/questions/25424622/authenticating-a-self-signed-certificate-for-ldaps-connection/25425078#25425078))isn't a good solution, but I never managed (or took the time) to find a better solution.
