### ISSUE TITLE
filter containing multiple "%s" fails

### ISSUE THREAD

**Issue by eannj** [heiglandreas/authLdap#129]
I'm using plugin version 1.5.1 on Wordpress 4.7.5.
I found out that a filter containing multiple "%s" references is not working, for instance the filter "(|(uid=%s)(mail=%s))" that allows login using either uid or mail LDAP attributes as login name.

The attached patch fixed the problem.
[patch.txt](https://github.com/heiglandreas/authLdap/files/1088543/patch.txt)

**Comment by heiglandreas** [comment]
Thanks for the patch. But as it uses ```sprint``` internally you can also use "%1$s" on both places. so when you alter your filter to ```(|(uid=%1$s)(mail=%1$s))``` that should also work without the patch…
