### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by ichbinder** [heiglandreas/authLdap#132]
Hi,

I try to connect wordpress to my OpenLDAP but after "Enable Authentication via LDAP" I get "500 Internal Server Error" after login. 

My logs:

> [Thu Jul 06 13:00:02.817662 2017] [:error] [pid 13104] [client 141.45.187.85:43416] [AuthLDAP] User 'heinz' logging in, referer: https://berlin.de/wp-login.php
[Thu Jul 06 13:00:02.817829 2017] [:error] [pid 13104] [client 141.45.187.85:43416] [AuthLDAP] about to do LDAP authentication, referer: https://berlin.de/wp-login.php
[Thu Jul 06 13:00:02.817900 2017] [:error] [pid 13104] [client 141.45.187.85:43416] [AuthLDAP] connect to LDAP server, referer: https://berlin.de/wp-login.php

WordPress version: 4.8

**Comment by heiglandreas** [comment]
Hi. Thanks for rausing that issue. Sorry for not getting back to you earlier. I hope you managed to at least get your website back to responding.

To solve the issue I'd need some more information though. First of all: Did you install the plugin via the plugin-manager or did you download it from somewhere? Which version of the plugin is it? Are you sure that the LDAP-extension is available on your system? Was thst the complete output of the logfile you postet there?

Thanks for providing more information. Feel free to contact me via email at andreas AT heigl DOT org

**Comment by heiglandreas** [comment]
When you used the plugin from the master-branch from GitHub there was an issue that thankfully has been resolved by @rossigee with #135.

So downloading and installing if from GitHub with a fresh download should fix the issue!

**Comment by ichbinder** [comment]
Sorry for my late answer, yes you are right I forgot to activate ldap for php5 in Debian:

- Install php5-ldap:
> sudo apt-get install php5-ldap

- Reboot apache
> /etc/init.d/apache2 restart

- Modify php.ini, and uncomment the line:
 > ;extension=php_ldap.so

I install master-branch and now every is fine.

Thank you for your help and your good plugin :).
