### ISSUE TITLE
Use of Version 2.0.0 with MultiSite-Installation

### ISSUE THREAD

**Issue by FireFrei** [heiglandreas/authLdap#144]
Hey there,

I just updated a WP-Multisite Installation from authLdap Version 1.5 to 2.0.
I noticed the changelog "This new release adds Multi-Site support. It will no longer be possible to use this plugin just in one subsite of a multisite installation!".
The update deleted all config, but thats already a known issue as I've seen on this issue tracker.

Furthermore I was using authLdap to separate logins for each site of the multisite.
So lets say, user in group A is editor of site A but not of site B. User of group B can edit site B, but not site A. This was possible before but now I can't find how to set this up anymore.
The plugin is now kind of "useless" for us as we need this separation. Is there any way to set it up this way again (maybe I'm blind :-) )?

Thanks for your advices!
Matthias

**Comment by heiglandreas** [comment]
Hi Matthias. Unfortunately not ATM! I'm working on exactly that feature right now but I do not have a release date yet!

**Comment by heiglandreas** [comment]
The best Option ATM would be to go back to v1.5

**Comment by heiglandreas** [comment]
This should now be fixed with v2.0.3 - That version allows to use the plugin as before *when it was configured like that before* - There's currently no possibility to make a new installation with v2.0.3 behave that way, but when it was configured like that before it uses the old config-scheme.
