### ISSUE TITLE
Call to undefined function Org_Heigl\AuthLdap\ldap_connect()

### ISSUE THREAD

**Issue by bersus** [heiglandreas/authLdap#147]
I have PHP 7.0 and php7.0-ldap extension installed but, when I try to login with my LDAP credentials, wordpress writes a debug log with the passwords in plain text and shows this error:
```
PHP Fatal error:  Uncaught Error: Call to undefined function Org_Heigl\AuthLdap\ldap_connect() in /var/lib/wordpress/wp-content/plugins/authldap/ldap.php:117
Stack trace:
#0 /var/lib/wordpress/wp-content/plugins/authldap/ldap.php(241): Org_Heigl\AuthLdap\LDAP->connect()
#1 /var/lib/wordpress/wp-content/plugins/authldap/src/LdapList.php(44): Org_Heigl\AuthLdap\LDAP->authenticate('wordpressUser', 'secret', '(uid=%s)')
#2 /var/lib/wordpress/wp-content/plugins/authldap/authLdap.php(244): Org_Heigl\AuthLdap\LdapList->authenticate('wordpressUser', 'secret', '(uid=%s)')
#3 /usr/share/wordpress/wp-includes/class-wp-hook.php(298): authLdap_login(NULL, 'wordpressUser', 'secret')
#4 /usr/share/wordpress/wp-includes/plugin.php(203): WP_Hook->apply_filters(NULL, Array)
#5 /usr/share/wordpress/wp-includes/pluggable.php(519): apply_filters('authenticate', NULL, 'wordpressUser', 'secret')
#6 /usr/share/wordpress/wp-includes/user.php(85): wp_authenticate('wordpressUser', 'secret')
#7 /usr/share/wordpress/wp-login.php(787): wp_si in /var/lib/wordpress/wp-content/plugins/authldap/ldap.php on line 117
```

**Comment by heiglandreas** [comment]
Did you get a notice that the ldap-extension is not available when configuring the plugin?

**Comment by bersus** [comment]
Yes, I can see the message "Caveat: The LDAP-extension is not loaded! Without that extension it is not possible to query an LDAP-Server! Please have a look at the PHP-Installation page".
Also, I executed the command "sudo apt-get install php7.0-ldap" to get the LDAP extension for my PHP 7.0

**Comment by heiglandreas** [comment]
Yeah. The thing is, you've got the extension installed on the server. But PHP doesn't (yet) know about it. You will most probably need an additional entry within `/etc/php/conf.d` for php-ldap that contains a line like `extension=php-ldap.so`. **Caveat:** The actual path and line vary between operating systems, so please consult your servers documentation of ask your favourite seach engine for something like "activate ldap php <your operating system>".

When the warning about the LDAP-extension is not showing anymore, the fatal error will be gone…

**Comment by bersus** [comment]
All configurations of PHP (apache2, cli, fpm, phpdbg) have a symbolic link to /etc/php/7.0/mods-available/ldap.ini but this file was empty. I have added a line `extension=ldap.so` to ldap.ini file and restarted apache2 and, now, ldap-extension doesn't notice any message and everything is working right.

Thank you very much!
