### ISSUE TITLE
No groups found when user DN contains parentheses

### ISSUE THREAD

**Issue by To6i** [heiglandreas/authLdap#153]
We are using the authLdap plugin successfully for a while now. But today a user with parentheses in his DN does not get the correct role assigned.

Group filter: (&(objectClass=group)(member=%dn%))
debug.log: [AuthLDAP] role from group mapping:

Other users without parentheses in their DN get the correct role based on their LDAP groups. It seems like some character escaping is missing.

**Comment by heiglandreas** [comment]
Thanks for mentioning! I'll dig into it and see to a quick fix! Though I might need to get back with some questions…

**Comment by To6i** [comment]
Great, just let me know if I can help with more detailed information.

**Comment by heiglandreas** [comment]
Just to clarify that: The parenthesis is *not* part of the username but of some other part  of the DN.

**Comment by To6i** [comment]
Yes, the usernames are alphanumerical characters only. The DN is as follows:
CN=some name (EXT),OU=...,OU=...,DC=...,DC=...

**Comment by heiglandreas** [comment]
I can't reproduce it… Would you mind sending me your configuration (without passwords of course). I'd be especially interested in the Filter and the Group-filter. That would really help me build a test to reproduce the issue!

**Comment by To6i** [comment]
Of course, is the configuration saved in a file or in the DB?

**Comment by heiglandreas** [comment]
It's in the DB but a screenshot would be OK.

**Comment by To6i** [comment]
I've sent you a screenshot of the configuration page by mail.

**Comment by heiglandreas** [comment]
Issue spotted! Thanks! A fix is on it's way.

**Comment by To6i** [comment]
It seems like the fix has never been integrated on to master. We have updated to verison 2.1.0 and the $dn variable is still not escaped and kill the request if it contains parentheses.

**Comment by heiglandreas** [comment]
Uppsss.... Sorry for the inconvenience and thank you for bringing that to my attention again!
