### ISSUE TITLE
Encrypt password used for binddn

### ISSUE THREAD

**Issue by popindavibe** [heiglandreas/authLdap#156]
Hello!

I have installed the plugin successfully, but realised that the password for the bind is stored in clear in the DB. Could it be possible to change current way of storing bind password, or let user bind with its own credentials?

Because my sites are reachable through FTP, a user with bad intentions could potentially upload PHP code allowing him to get the LDAP info, including bind account credentials and further request other info on the LDAP server using that account. I would like to prevent that.

**Comment by heiglandreas** [comment]
Hi. 

Yes, I can see that that is a potential security hole. But: What way would you prefer to use for encrypting the password for the initial bind? Because at one point it definitely needs to be decrypted. So a malicious user could also upload a script that hooks into the decryption and can still gain access to the cleartext password. At least to my knowledge. That for sure is a risk I am aware of. 


But having other people upload untrusted files is per se a security risk. How do you know they don't upload a script that hooks into wordpress' authentication filter and passes the *users* password along with their username. That is a far more serious issue than gaining access to a password that should only be usable from a certain machine...

So I'm not really seing an absolutely secure way of storing the password (that is needed in cleartext for the `ldap_bind`) in a way that someone with access to the server can't read it. So as long as there is no secure way I'm not going to elude someone into a false sense of security.  I might be wrong on that and if you can correct me that'd be great.

**Comment by popindavibe** [comment]
Thanks for the quick reply, really appreciated.
As I was looking more into this, I was reaching to the same conclusions.

The only way I would see this working would be do the bind on the fly with the user credentials. That would imply to store somewhere what the RDN should be for users so that it can be appended to the username when submitting credentials. And then, basically using the user's credentials to bind and validate itself. 

No binddn credentials stored any more.

I realise this would probably induce a big change in the code though...

Maybe I should look into other possibilities, but it looks like allowing users to manage plugins is pretty much letting them do anything they want one way or another. I am just starting on WordPress, I could appreciate any insights you might have on this.

**Comment by heiglandreas** [comment]
You will still need binddn-credentials to search for the DN of the user as user can be stored somewhere within the directory-tree. Therefore you need to bind to be able to search for the user that tries to log in. As by now most LDAP-servers don't allow an anonymous bind you will need the binddn that is used to sesrch for the user that tries to log in. 

Only when you know exactly where the users are located within the Directory tree and the users are using the last part of the DN to log in you might be able to skip that first bind and only use the users credentials. But that is explicitly *not* the scope of this plugin. This plugin gives you the freedom to use whatever directory structure that you might encounter and whatever you want the user to use for logging in. This freedom though comes with the price that you need a binddn. 

You (or your directory admin) could create a user for this initial binding that can only read the necessary attributes and only allow binds from the WordPress-server to the LDAP to not allow people to read other informations once they gain access to the server.

**Comment by popindavibe** [comment]
Hmm, I understand. Indeed my idea was to dramatically reduce the scope of the plugin in order to keep both the plugin and the ability to install/delete plugins for my users. But as you point out this would be counter-productive.

I can look further into LDAP ACLs to see how far I could get reducing the rights of the bind user a bare minimum. Otherwise my guess is to either:
- remove the authLDAP plugin and use local user + FTP / plugins access 
- or keep the plugin and prevent ftp access + control which plugins could be installed.

In any case, thank you for the prompt answers, and kudos for the plugin, it works asolutely great, and I realise that the limitation I am facing come from WordPress design itself.

**Comment by popindavibe** [comment]
Hey,
A bit of a feedback. I've been playing with LDAP ACL following your suggestion and I think I pinned it. I put it here in case it may prove useful for others:

1. I created a special entry for the LDAP bind: cn=wordpress,ou=bind,dc=example,dc=com
1. I then added an ACL rule and edited the next one (after the first one filtering access to passwords) :
```
olcAccess: {1}to dn.subtree="ou=people,dc=example,dc=com" attrs=entry,uid by ssf=128 dn="cn=administrator,,dc=example,dc=com" write by ssf=128 dn.children="ou=bind,dc=example,dc=com" read by ssf=128 users read by ssf=128 anonymous auth by * none
olcAccess: {2}to dn.subtree="ou=people,dc=example,dc=com" by ssf=128 dn="cn=administrator,dc=example,dc=com" write by ssf=128 dn.children="ou=bind,dc=example,dc=com" none by ssf=128 users read by ssf=128 anonymous auth by * none
```
Now I can use that user to search for a uid, and that's all really. It is also not possible to filter all uids using the bind user. That looks ok! Thanks again!
