### ISSUE TITLE
some bug in processing ldap groups

### ISSUE THREAD

**Issue by olszeww0** [heiglandreas/authLdap#157]
In file authLdap.php is: 
        /// my  variable $groups contains
        /// array(2) { ["count"]=> int(1) [0]=> array(2) { ["count"]=> int(0) ["dn"]=> string(73) "CN=site-admin,OU=sitename,OU=NewUsers,DC=example,DC=com" } }
        // $authLDAPGroupAttr contains "dn"
        // and below have no chance to work with content of my variable $groups,
    $grp = array();
    for ($i = 0; $i < $groups ['count']; $i++) {
        for ($k = 0; $k < $groups[$i][strtolower($authLDAPGroupAttr)]['count']; $k++) {
            $grp[] = $groups[$i][strtolower($authLDAPGroupAttr)][$k];
       }
    }

**Comment by heiglandreas** [comment]
What is your exact configuration and what is your actual issue?

**Comment by olszeww0** [comment]
I think this bug is now obsolete.
