### ISSUE TITLE
[AuthLDAP] User '' logging in

### ISSUE THREAD

**Issue by Adamcina** [heiglandreas/authLdap#160]
This is not a real issue, but an asking for help.

I'm running FreeIPA server on Centos 7, have a few WordPress websites on other Centos 7 server as well, and i'm looking to establish SSO for my WordPress users across those websites and some other apps. In order to do that i'm trying to configure AuthLDAP properly.
This is my `auth_gssapi.conf`:
```
<Location "/wp-login.php">
	AuthType GSSAPI
	AuthName "GSSAPI Single Sign On Login"
	GssapiCredStore keytab:/usr/local/apache/conf/http.keytab
	GssapiBasicAuthMech krb5
	Require valid-user
</Location>
```
As a AuthLDAP URI i've tried this and many many other combinations:
`ldap://admin_user_name:admin_password@ipa-server.example.com:389/dc=ipa-server,dc=example,dc=com`

When i visit my WordPress website at /wp-admin/ apache's error log gives this:
```
[Thu Oct 18 09:49:41.265710 2018] [:error] [pid 1297:tid 140477911234304] [client my_ip_address] [AuthLDAP] User '' logging in
[Thu Oct 18 09:49:41.265820 2018] [:error] [pid 1297:tid 140477911234304] [client my_ip_address] [AuthLDAP] Username not supplied: return false
```
I've did `telnet` and `ldapsearch` tests from my WordPress websites server to a FreeIPA server, these are results:
```
[root@server ~]# telnet IPA-SERVER_DOMAIN_IP_ADDRESS 389                                      
Trying IPA-SERVER_DOMAIN_IP_ADDRESS...
Connected to IPA-SERVER_DOMAIN_IP_ADDRESS.
Escape character is '^]'.
Connection closed by foreign host.
```
ldapsearch gives response with a bunch of text, and i won't copy all of those, but just the end:

```
......
# search result
search: 2
result: 0 Success

# numResponses: 115
# numEntries: 114
[root@server ~]#
```
so it looks like servers are able to communicate.
I'm trying to SSO to WordPress from my Windows 7 machine, and i have got installed MIT Kerberos Ticket Manager and successfully obtained tickets:
![mit kerberos](https://user-images.githubusercontent.com/3274197/47143076-ab0d5200-d2c4-11e8-89e5-0d4e4e1244eb.jpg)

so, FreeIPA, my Mozzila browser (for Kerberos negotiation process) and everything else is configured as it should be.

I've been investigating and trying last few days to make this to work but nothing has helped. I hope that i've given enough information. Can you please tell me what am i missing?

**Comment by heiglandreas** [comment]
Hey Adam. 

For me it looks like you are mixing two different things up. The one is the single sign on with kerberos and the other one is the LDAP authentication. The AuthLDAP-Plugin is only desigend to allow people to log into a wordpress site using their LDAP-credentials. But those credentials need to be put into the wordpres login form.

But as far as I see it you want something different. You want the user to be logged into WordPress automatically using the Kerberos token. That's something completely different as the user does not need to provide any credentials at all. So you would need a plugin that checks the Kerberos-Token against the Kerberos-Server and then decides whether the user may enter WordPress or not. That's not the scope of AuthLDAP (as LDAP is not involved at all in that process)

In a quick search I only found one plugin that mentions Kerberos and that is for ActiveDirectory (https://wordpress.org/plugins/next-active-directory-integration/). So ot looks like you either need to write it yourself or need a different approach :-(

Sorry that I can't help you there.

**Comment by Adamcina** [comment]
Andreas, thank you for your quick answer. Yes, you're right, i've been mixing these things, because i've never been in touch with LDAP/Kerberos before so it's a little bit tricky for me to understand properly how things work. But your answer has helped me to get a clearer picture.
I think that i will follow LDAP as there is a plugin already that you've created.
Thanks!
