### ISSUE TITLE
AuthLDAP and bbpress 

### ISSUE THREAD

**Issue by wixaw** [heiglandreas/authLdap#164]
Hello,

We have a issue between AuthLDAP and bbpress, 
When the person with the role keymaster (admin forum) connects, he loses his role and becomes a participant again
Would not there be a rule that erases the roles at each connection?

Thanks in advance
William

**Comment by heiglandreas** [comment]
It depends on how you configured authLDAP. For example when you set the `default role` to "participant"  and also activated `group over user` that will happen.

Would you mind posting (or send it to andreas AT heigl DOT org) your (sanitized) config? Especially the group-configuration part would be interesting . I don't need passwords or filters.

That would help me in finding the issue!

**Comment by heiglandreas** [comment]
Have you tried disabling the use of groups? When you do not need LDAP group-mapping but have enabled the groups-functionality the authentication-process will overwrite your manual group-management. Alternatively you can disable **LDAP Groups override role of existing users** to keep your manually assigned roles.

**Comment by wixaw** [comment]
If is this option "Map LDAP Groups to wordpress Roles?" it's uncheck

**Comment by wixaw** [comment]
Hello,
What about our issue ? 

Thank's

**Comment by heiglandreas** [comment]
Thanks for your patience! Would you mind sending a screenshot of your complete configuration to info [AT] authldap [DOT] net? That would help me a lot in debugging your issue. Thanks

**Comment by wixaw** [comment]
I can put it here, no problem

![image](https://user-images.githubusercontent.com/7153125/49137002-8a84de80-f2eb-11e8-8340-50418b05df2a.png)

**Comment by heiglandreas** [comment]
Thank you! Do you have enabled authLdap-Debugging and can provide me with an excerpt of the error-log?

**Comment by wixaw** [comment]
Here is log but i understand bug ! 

> [28-Nov-2018 08:25:22 UTC] [AuthLDAP] connect to LDAP server
> [28-Nov-2018 08:25:23 UTC] [AuthLDAP] LDAP authentication successfull
> [28-Nov-2018 08:25:23 UTC] [AuthLDAP] Existing user, uid = 3
> [28-Nov-2018 08:25:23 UTC] [AuthLDAP] Existing user's role: author
> [28-Nov-2018 08:25:23 UTC] [AuthLDAP] The LDAP user has an entry in the WP-Database
> [28-Nov-2018 08:25:23 UTC] [AuthLDAP] user id = 3

With once role (keymaster), authLDAP keep the forum role, with two role (author+keymaster)(co-admin+keymaster)(...+keymaster), the second role is overwritten
We are going forward  ! :)

**Comment by heiglandreas** [comment]
Ah! OK. The thing is that WordPress internally uses one role. I suspect that the two-role thing is something specific to BBPress that I have not yet encountered. 

Thanks for helping me digg deeper into it. I need to investigate that a bit further!

So long you might want to comment out line 340 in authLdap.php that reads like this:

```php
        $user_info['role'] = $role;
```

That should eliminate setting the role for the user. You might need to add the role for new users manually then though!

**Comment by wixaw** [comment]
Yes it's work ! 
The existing user role is keep and new user is 'Subscriber, Participant' . That suits us.

**Comment by heiglandreas** [comment]
So this can be closed then....

**Comment by wixaw** [comment]
Humm, Without modification on the plugin it means that we will not be able to update it any more?

**Comment by heiglandreas** [comment]
Ah. OK. I'll figure out something...
