### ISSUE TITLE
Problem with Group-Filter

### ISSUE THREAD

**Issue by heiglandreas** [heiglandreas/authLdap#168]
This Question was added to issue #43 by @8Cris1:

Hi, I'm sorry if I open this discussion again. I need to authenticate users through 'uid'. The users are in a LDAP group in this form:

cn name-of-the-group

member:
uid=username1,ou=sub-group-name1,ou=group-name,dc=domain-name,dc=it
uid=username2,ou=sub-group-name2,ou=group-name,dc=domain-name,dc=it
uid=username3,ou=sub-group-name3,ou=group-name,dc=domain-name,dc=it

objectClass:
groupOfNames
top

I'm wondering which fields and how I have to compile in authLdap plugin, considering the authentication is based on 'uid' and password. I'm a little bit confused. Thank you.

**Comment by heiglandreas** [comment]
Hey @8Cris1 - I assume you already got the authentication part covered and now you are wondering on how to configure the group-matching part.

As already mentioned in #43 you can not only use the `%s`-placeholder that translates to the users UID but also `%dn% which translates to the users Distinguished Name. Which is what the field `member ` seems to contain. So the following filter should be able to retrieve the groups the user is a member of:

    (&(objectClass=groupOfNames)(member=%dn%))

Does that help you?

**Comment by 8Cris1** [comment]
Thanks for your reply. I set all fields as in the figures:
![authLdap1](https://user-images.githubusercontent.com/38976447/55084772-c6fff580-50a5-11e9-8877-646e33959a5a.png)

![authLdap2](https://user-images.githubusercontent.com/38976447/55084025-cadf4800-50a4-11e9-8fab-c4db10f9b118.png)

but it seems that *all* the users under the base path specified into LDAP URI are successfully authenticated. I want that only users specified into "Group-base" are be able to authenticate successfully.

**Comment by heiglandreas** [comment]
I've just relesaed a new version 2.1.1 which includes escaping the group-filer attributes. Would you mind giving that a try and get back with the result? Thanks for your help!

**Comment by 8Cris1** [comment]
Hi, I updated to 2.1.1 but it seems to continue to ignore the "Group-base" specification. In fact also other users not present in that "Group-Base" are able to authenticate successfully. This probably happens because these users are still present into base path.

**Comment by heiglandreas** [comment]
Oh! The Group-Base can be left empty if it's also under the BaseDN of the LDAP-URI. And then you will need to map your defined group to one of the access-levels of WordPress.

So given your group hsa a gidNumber of `10000` and a cn of `myGroup`  you can either set `groupAttribute` to `gidNumber` and insert the gidNnumber into the field next to your required WordPress-Level or you set `groupAttribute` to `cn` and insert the CN into the field next to the WordPress-Level.

If you uncheck the *LDAP group override roles of existing users* -option you can set any WordPress role after a user logs in and they will stay that way but only people from one of the groups marked will be able to log in.

**Comment by heiglandreas** [comment]
Oh! The Group-Base can be left empty if it's also under the BaseDN of the LDAP-URI. And then you will need to map your defined group to one of the access-levels of WordPress.

So given your group hsa a gidNumber of `10000` and a cn of `myGroup`  you can either set `groupAttribute` to `gidNumber` and insert the gidNnumber into the field next to your required WordPress-Level or you set `groupAttribute` to `cn` and insert the CN into the field next to the WordPress-Level.

If you uncheck the *LDAP group override roles of existing users* -option you can set any WordPress role after a user logs in and they will stay that way but only people from one of the groups marked will be able to log in.

**Comment by 8Cris1** [comment]
This is the scenario:

base-node
|----groups
|----|-----group1
|----|-----group2
|----|-----group3
|----people
|----|-----organizationalUnit1
|----|-----|------------------user1
|----|-----|------------------user2
|----|-----organizationalUnit2
|----|-----|------------------user3
|----|-----organizationalUnit3
|----|-----|------------------user4
|----|-----|------------------user5
|----|-----|------------------user6

In "LDAP URI" field I specified the URL and the base_node path. Now, suppose "user2" and "user4" are in "group2". I would like that only these users (into group2) can make successfully auth. As you can see user2 and user4 already exist in the base_node path.
Following your suggestions i set:
![authLdap3](https://user-images.githubusercontent.com/38976447/55178702-2fbe9f00-5186-11e9-877f-1bc6d50e26f7.png)

but it still not work...
I feel we are close to the solution, thanks

**Comment by 8Cris1** [comment]
Hi, any update?

**Comment by heiglandreas** [comment]
I just had a more in depth look at the information you gave me. And it should work when you set the group filter to `(&(objectClass=groupOfNames)(member=%dn%))` as already mentioned and the role-group mapping of Administrator to `group2` when your group-attribute is set to `cn`. 

The path-part of the LDAP-URI should be `base-node` and **not** contain either `groups` or `people`.

Then it *should* work...

**Comment by 8Cris1** [comment]
Dear Andreas, sorry for this very late feedback but I had archived the project. Now to tell you that your solution worked!
Thank you very much for your support

**Comment by heiglandreas** [comment]
Hey @8Cris1 : Great to hear that it worked in the end :tada:! Thanks for the feedback! I'll then close this issue.
