### ISSUE TITLE
Stop Password-Change Email on password-Update via LDAP

### ISSUE THREAD

**Issue by breti** [heiglandreas/authLdap#170]
#80 seems to be back: An E-Mail is sent after first login with LDAP credentials.

WordPress 5.1.1, authLdap 2.1.0

**Comment by heiglandreas** [comment]
Does that happen when the user was created first in WordPress and not during the Login-Procedure? Are there any other plugins installed in the WordPress instance or did you test that just with WordPress 5.1.1 and authLdap 2.1.0?

**Comment by heiglandreas** [comment]
Because codewise I can not find a problem and I can not reproduce it here on my end....

**Comment by breti** [comment]
It is an older Wordpress installation with many plugins that has now been moved to a new server. Because the old LDAP plugin is not compatible with PHP 7, now your (really great!) plugin is used. The users had already entered the Wordpress installation through the old plugin.
The mail now seems to be sent the first time the user logs in via your plugin, then not again.

**Comment by heiglandreas** [comment]
Ah. OK. Then the users are converted to authLDAP-users on their first login and - depending on where in the process the email is sent - that overlaps wrongly. I'll have a look into it later to fix that. Expect a new release within this week
