### ISSUE TITLE
Duplicate user overwrite

### ISSUE THREAD

**Issue by Westie** [heiglandreas/authLdap#172]
Hi,

I have encountered the following issue on a site which I intend to use LDAP on - thankfully I haven't made this feature live yet but once I have patched this issue, it will be my intention

If I have an already existing user by the username of `david`, whose e-mail address is david@westie.sh, and I have a user within LDAP whose username is `david` but whose e-mail is david@typefish.co.uk, there exists the situation where one account can be taken over by another, separate account.

(The ID of this user remains the same - data/roles are overwritten)

Now, I see two ways around this.

1) If a user exists with a different e-mail, make username different. Perhaps `uid` + a random ID.
2) Pass *all* LDAP usernames through a sprintf function, so `david`, when passed through `ldap_user_%s` becomes `ldap_user_david`

Option 1 can become very complex very quickly, whilst option 2 allows for forcing LDAP users to have a fixed prefix, plus adding in a check to disallow other users from registering LDAP-type usernames.

I am personally going to look into option 2, if that's okay with you?

**Comment by Westie** [comment]
Actually, I have come across a novel way of fixing this

FreeIPA assigns objects a UUID, I have decided to use this as the login identifier and as such, conflicts have been resolved.

**Comment by heiglandreas** [comment]
So this is not an issue any more?

**Comment by Westie** [comment]
Well, it still is an issue, but I'm not necessarily sure if it's now an issue that has responsibility with authLdap or FreeIPA

I like to assign a user to one or two groups.

User A is the chairman, and as a result, is in group WP Admin and Mailserver.

Sadly, since FreeIPA does not support searching for groups based on someone who is a derived member (which is frankly, weird) then I've had to assign each user to WP groups.

I might look into fixing this properly, but GUIDs matches how Nextcloud has it.

Perhaps a warning should be placed into the README instead?

**Comment by heiglandreas** [comment]
Where do you want to assign the user to one or more groups?

authLDAP eithre creates a user in WordPress when no user with the username defined by the *User-ID Attribute*. If a user by that username already exists, it will be updated to an LDAP-Based user. Currently that is intended behaviour, but you are right that that is a security problem when introducing LDAP-Authentication late on a project where users have already been added to WordPress.

I will implement a check whether an already existing user is marked as an LDAP user and if not, the default login-mechanism will apply. Though in the short run that will remove the ability for a user with the same username to log into WordPress via LDAP authentication. Therefore this check will be optional and not enabled by default.

Additionally an appropriate warning will be added to the README. Thank you for bringing this to my attention!

I will

**Comment by heiglandreas** [comment]
The new version with the extra checkbox is now in the git master-branch. I see to it that I'll create a release within the next few days that will then also be available right within the WordPress-Updater

**Comment by johnmhancock** [comment]
I had an issue with this flag in a new installation of wordpress (only admin user) that wouldn't allow any ldap user who successfully authenticates to complete the login.  Once I remove the checkmark it did allow the user to be created and login to the site.  Is that the desired behaviour for the "Do not authenticate existing WordPress-Users" option?
