### ISSUE TITLE
New users can't login with "Do not authenticate existing WordPress-Users" Option checked.

### ISSUE THREAD

**Issue by johnmhancock** [heiglandreas/authLdap#177]
I had an issue with this flag in a new installation of wordpress (only admin user) that wouldn't allow any ldap user who successfully authenticates to complete the login.  Once I remove the checkmark it did allow the user to be created and login to the site.  Is that the desired behaviour for the "Do not authenticate existing WordPress-Users" option?

_Originally posted by @johnmhancock in https://github.com/heiglandreas/authLdap/issues/172#issuecomment-556414425_

**Comment by heiglandreas** [comment]
Actually it's not the desired behaviour. 

that flag should prohibit users that were created in WordPress to not log in. I need to dig into that and check what's going wrong there and why.

Thanks for notifying me!

**Comment by heiglandreas** [comment]
Can you give me a bit more detail on that issue?

Did you create the users manually before they logged in via LDAP? Can you provide me the authLDAP log-output? (feel free to send it to authldap AT heigl DOT org if you're not comfortable posting it here)

**Comment by johnmhancock** [comment]
I did not create the user before they logged in via Ldap.

I created the first wordpress administrator during the initial installation, and then set up the authLdap plugin with some group restrictions to set who could log in.   When I tried to log in with one of those ldap accounts that had a different name than the admin account, I could not.  I cleared the "Do not authenticate existing WordPress-Users"  and was able to log in with the account and it was created.

**Comment by johnmhancock** [comment]
I've sent the log.  For the ticket, the condensed version is:

```
[AuthLDAP] User 'username' logging in
AuthLDAP] about to do LDAP authentication,
referer:
[AuthLDAP] connect to LDAP server, referer:
AuthLDAP] LDAP authentication successfull,
referer:


```

After disabling the option, the log then shows the above entries and:

```
[AuthLDAP] Array\n(\n    [administrator] =>
XXX,XXXX\n    [editor] => \n    [author] => \n    [contributor] => \n
   [subscriber] => \n)\n, referer:
AuthLDAP] Array\n(\n    [administrator] =>
XXX,XXXX\n    [editor] => \n    [author] => \n    [contributor] => \n
   [subscriber] => \n)\n, referer:
 [AuthLDAP] Group Filter:
[AuthLDAP] Group Base: , referer:
AuthLDAP] LDAP groups:
["xxx","xxxxx","xxxxxxx"]
AuthLDAP] Role from LDAP group: administrator,
referer:
[AuthLDAP] role from group mapping: administrator,
referer:
[AuthLDAP] The LDAP user does not have an entry in
the WP-Database, a new WP account will be created, referer:
[AuthLDAP] user id = X, referer:
```

**Comment by johanwendin** [comment]
I happened upon this problem as well, it can be fixed by changing row 308 in authldap.php from:

```php
if (! get_user_meta($uid, 'authLDAP')) {
```

to:

```php
if (get_userdata($uid) && !get_user_meta($uid, 'authLDAP')) {
```

**Comment by mherrb** [comment]
Hi,
Same problem here. the fix by johanwendin above works for us.
