### ISSUE TITLE
issue wit complex filters

### ISSUE THREAD

**Issue by GUHU0433** [heiglandreas/authLdap#179]
Hi, thank you very much for the plugin. It works very well for me, runnung again an Open-Ldap-Server. I have only two issues:
One issue is that I cannot use complex filters like (&(objectclass=posixAccount)((!(uid=%s)(mail=%s)))
 I got these messages:

Warning: sprintf(): Too few arguments in /kunden/563849_51429/webseiten/wordpress/wp-content/plugins/authldap/ldap.php on line 247

Warning: ldap_search(): Search: Protocol error in /kunden/563849_51429/webseiten/wordpress/wp-content/plugins/authldap/ldap.php on line 202

**Comment by heiglandreas** [comment]
Have you tried using `%1$s` instead of `$s`? That should do the trick...

**Comment by GUHU0433** [comment]
thanks. No, this is not working for me.
Now i cannot log in anymore :(

**Comment by heiglandreas** [comment]
I more or less described your exact use-case in the [README-file](https://github.com/heiglandreas/authLdap#server-settings). Have a look at **Filter**

**Comment by GUHU0433** [comment]
Warning: ldap_search(): Search: Bad search filter in /kunden/563849_51429/webseiten/wordpress/wp-content/plugins/authldap/ldap.php on line 202

**Comment by GUHU0433** [comment]
So, i deactivated all plugins via database, then check all entries - there was a typo :)
Everything ist working well now.
Thank you very much!
