### ISSUE TITLE
Error returned from LDAP with unknown USER "test"

### ISSUE THREAD

**Issue by Markstener** [heiglandreas/authLdap#180]
Hi

We are having trouble getting authLDAP to work in our WPMU. The specific error you can see in the log I got from our IT Dep. 
**Log:**
Apr  1 10:28:24 ldap-uit02.uio.no slapd[119878]: conn=672482 op=0 BIND dn="uid=wordpress,cn=users,cn=system,dc=uit,dc=no" method=128
Apr  1 10:28:24 ldap-uit02.uio.no slapd[119878]: conn=672482 op=0 BIND dn="uid=wordpress,cn=users,cn=system,dc=uit,dc=no" mech=SIMPLE ssf=0
Apr  1 10:28:24 ldap-uit02.uio.no slapd[119878]: conn=672482 op=0 RESULT tag=97 err=0 text=
Apr  1 10:28:24 ldap-uit02.uio.no slapd[119878]: conn=672482 op=1 SRCH base="cn=people,dc=uit,dc=no" scope=2 deref=0 filter="(uid=test)"
Apr  1 10:28:24 ldap-uit02.uio.no slapd[119878]: conn=672482 op=1 SRCH attr=uid
Apr  1 10:28:24 ldap-uit02.uio.no slapd[119878]: conn=672482 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=
Apr  1 10:28:24 ldap-uit02.uio.no slapd[119878]: conn=672482 op=2 UNBIND
Apr  1 10:28:24 ldap-uit02.uio.no slapd[119878]: conn=672482 fd=34 closed

--------------------------------------------------
Somehow search in db is done for this "(uid=test)" which does not excist. User testet has used a very different username? Have no idea where "test" comes from.

I am sorry, but I am not a programmer så I'm a slightly out of my depth here.

**Comment by heiglandreas** [comment]
Hey there. Thanksnfor reaching out. Can you post your current config for authLdap (screenshot without password) and perhaps also the content of the PHP log after activating authLDap logging

**Comment by Markstener** [comment]
Hi, and thank you so much for replying!
Because I am a WP-admin authLDAP found me in the wp db – so I get logged in that way. It seems it "reads" my username. When I use a LDAP test account that does not have a wp account "lfi000" in this case, it returns an error i LDAP log that "test" was not found.. Anyway. Here is s screenshot og setup. Full LDAP URI added in red + extraction of log when test was done.

[AuthLDAP-log.txt](https://github.com/heiglandreas/authLdap/files/4423187/AuthLDAP-log.txt)
![AuthLDAP-ScreenDump](https://user-images.githubusercontent.com/63056637/78292848-f8689800-7527-11ea-86ca-aa40ddb9913f.jpg)

Again, thank you so much for getting back. We are hoping to have this up for our students in these home-study times, but they need to able to use their AD-user accounts

**Comment by heiglandreas** [comment]
You are trying to access an ActiveDirectory. Have you tried setting the filter to `(sAMAccountName=%s)`? The problem might be that AD does not know the `uid`-attribute. Or, if people should use their Email-Address for login, use f.e. `(mail=%s)` as filter. If you want to use multiple attributes to search for, you need to use `%1$s` instead of the `%s`. So to allow people to use either their login **or** their Email-Address for logging in you can use the filter `(|(sAMAcountName=%1$s)(mail=%1$s))`. For more details on which attributes exists you should have a chat with your AD-Admin. They should be able to tell you what fields you can and can not use ;-)

**Comment by Markstener** [comment]
Hi, and thank you!
Your suggestion for filter seems to have done the trick! Very happy about that. If I can bother you one more time: Users have to use ad alias (full mail address) to logg in. When user is generated in WP ad username is set as username in WP, but can not be used to login? User must continue to use ad alias to login? Is it just me or is that strange?

Again, thank you so much for your speediness and help. It is very much appreciated.
