### ISSUE TITLE
Update to 2.4.0 causes fatal error

### ISSUE THREAD

**Issue by patriclougheed** [heiglandreas/authLdap#185]
Love the plugin! Best ldap for wordpress but...

PHP Fatal error:  Uncaught Error: Class 'Org_Heigl\AuthLdap\LdapUri' not found in /wordpress/wp-content/plugins/authldap/authLdap.php:144#012Stack trace:#012#0 /wordpress/wp-content/plugins/authldap/authLdap.php(252): authLdap_get_server()#012#1 /wordpress/wp-includes/class-wp-hook.php(287): authLdap_login(NULL, 'demo', '****')#012#2 /wordpress/wp-includes/plugin.php(206): WP_Hook->apply_filters(NULL, Array)#012#3 /wordpress/wp-includes/pluggable.php(539): apply_filters('authenticate', NULL, 'demo', '****')#012#4 /wordpress/wp-includes/user.php(95): wp_authenticate('demo', '****')#012#5 /wordpress/wp-content/plugins/theme-my-login/includes/actions.php(432): wp_signon(Array, true)#012#6 /wordpress/wp-includes/class-wp-hook.php(287): tml_login_handler('')#012#7 /wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)#012#8 /wordpress/wp-includes/plugin.php(478): WP_Hook->do_action(Array) in /wordpress/wp-content/plugins/authldap/authLdap.php on line 144

Rolling back to 2.3.1 restores authentication

**Comment by heiglandreas** [comment]
Dammit! Tested it and everything was fine but I seem to have forgotten to deactivate a plugin. Fix is on its way!

**Comment by heiglandreas** [comment]
Should be fixed now with v2.4.2

**Comment by heiglandreas** [comment]
Can you cornfirm the fix?

**Comment by patriclougheed** [comment]
Working now. Thanks!
