### ISSUE TITLE
Blank page after successful login

### ISSUE THREAD

**Issue by frederikhegger** [heiglandreas/authLdap#19]
Dear Mr. Heigl,
it seems that I configured the plugin correctly and I am able to login. But after the login I just get a blank page.

I am using the wordpress version 4.0 and plugin version 1.3.0.

My group settings look like the following:

* Groups for Roles
 * Group-Attribute: gidNumber
 * Group-Filter: (&(uid=%s)(gidNumber=102))

* Role - group mapping
 * Administrator: 102

I enabled the debug information, but do not see anything.

Do you have any idea what the problem could be?

**Comment by brammeleman** [comment]
It could be that the Group-Filter setting is not properly saved in the wp settings table. Could you try again with the zip download from github?

**Comment by heiglandreas** [comment]
Looks like you have an issue there with the group filter. Just to make things clear: You have a group in LDAP where the users loginname is held in an attribute called ```uid```? So with a tool like 
```ldapsearch``` you would get a result for the following query: 

    ldapsearch -h <your.ldap.host> -b=<your,search,base> (&(uid=<loginname>)(gidNumber=102))

If that is **not** the case, then there is an issue with the group filter. I'd expect it do look more like ```(&(memberUid=%s)(gidNumber=102)```. But without knowing wich attributes are provided in the group with gidNumber 102 that is rather difficult to say. Can you provide some more information?

**Comment by frederikhegger** [comment]
@brammeleman I tried both, cloning the sources and the zip. In both cases, the plugin was not detected at all. I tried to rename the folder according to the PHP file inside the folder (i.e. authLdap.php). No success.

@heiglandreas the ldapsearch command you provided did not work. But with differently arranged paramters it worked:

     ldapsearch -x '(&(uid=<loginname>)(gidNumber=102))' -h <your.ldap.host> -b <your,search,base>

I also realized that the group filter is wrong and I changed this to the default value. With this expression I did the following ldapseach:

     ldapsearch -x '(&(objectClass=posixGroup)(memberUid=<loginname>))' -h ldap.inf.fh-bonn-rhein-sieg.de -b dc=fh-bonn-rhein-sieg,dc=de

This returns several entries, basically in the following format:

     objectClass: posixGroup
     gidNumber: 10002 
     memberUid: <myloginname>
     memberUid: <other_usernames>
     ....

     objectClass: posixGroup
     gidNumber: 10022 
     memberUid: <myloginname>
     memberUid: <other_usernames>
     ....

     objectClass: posixGroup
     gidNumber: 50016
     memberUid: <myloginname>
     memberUid: <other_usernames>
     ....

I thought, that I then just choose one of the gidNumbers and add them e.g. to the "Administrator" textfield of the "Role - group mapping". 

Am I wrong?

Thanks for your help.

**Comment by heiglandreas** [comment]
@frederikhegger Thats correct! The gitNumber you got there goes into the Administrator (or whatever group)-field.

And your ```groupFilter```-Setting should then be ```(&(objectClass=posixGroup)(memberUid=%s))```. 

That should then work out.

Please give us a short feedback whether that works or not.

**Comment by frederikhegger** [comment]
Yes, of course. I already set the groupFilter to (&(objectClass=posixGroup)(memberUid=%s)). But I does not work.

I am using version 1.3.0 from the wordpress plugin website. I tried to download the code (v1.3.1) from github directly, but then the plugin does not get detected at all in wordpress.

**Comment by heiglandreas** [comment]
Sorry for stating the obvious, but you did set the Admin-Group-ID to ```10002```? As in your first example you stated ```102```? Can you give us the values you provided for the configuration? I have set up the plugin here and simply added the host and the admin-groups gidNumber. Everything else I left clear and it works for me. With - as far as I can see - the same setup that you have. OpenLDAP and more or less default Schema.

**Comment by frederikhegger** [comment]
No problem. I am very happy to get immediate support. 

To aviod ambiguity, here are my current settings:

General Server Settings
* LDAP URI: set to the correct host
* Filter: (&(uid=%s)(|(uid=<username_1)(uid=username_2)))   // I just want to allow to users access and unfortunately there is not group where only those two are in

Settings for creating new Users
* Name-Attribute: displayName
* Second Name Attribute: left empty
* User-ID Attribute: uid
* Mail Attribute: mail
* Web-Attribute: left empty

Groups for Roles
* Group-Attribute: gidNumber
* Group-Filter: (&(objectClass=posixGroup)(memberUid=%s))

Role - group mapping
* Administrator: 10022
* Editor: left empty
* Author: left empty
* Contributor: left empty
* Scubscriber: left empty

And I used 10002 instead of 102.

I also tried your approach, namely leaving everything empty, except host and the admin-group gidNumber. But same here, no success.

**Comment by heiglandreas** [comment]
Can you - just to eliminate the odds - set the Filter just to ```(uid=%s)```?

**Comment by frederikhegger** [comment]
No luck either.

**Comment by heiglandreas** [comment]
That is so strange.... I suppose the error logs from the web server don't give a clue either. Did you turn on debugging?  And If so, could you post the log-entries? you can also do so to andreas AT heigl DOT org

**Comment by frederikhegger** [comment]
After adding some additional debug outputs to the code, we finally found the problem:

"Sorry, that email address is already used!"

The problem was that the we already had local users in the database which had the same email address as the accounts we used to login via ldap.

But thank you very very much for your immediate support.

**Comment by heiglandreas** [comment]
Glad that it had been THAT easy ;-) 

Thanks for mentioning!
