### ISSUE TITLE
Error from PHP - bind was not successfull: Can't contact LDAP server

### ISSUE THREAD

**Issue by phodchara** [heiglandreas/authLdap#193]
Hi Andreas,

I would like you to advise a setting of AuthLDAP. On bellow's an information that we got when User try to login on WordPress

**1. AuthLDAP Setting**
- General Usage of authLDAP
> Enable Authentication via LDAP?: Yes
> Debug AuthLDAP?: Yes
- General Server Settings
> LDAP URI: ldaps://uid=wordpress,OU=WordPress,OU=_TurnOnMail,OU=SystemAccountdc=nist,dc=ac,dc=th:secret@ldap.nist.ac.th/OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th
> Filter: (uid=%s)
- Settings for creating new Users
> Name-Attribute: name
> User-ID Attribute: uid
> Mail Attribute: mail
> Default Role: Subscriber

**2. Error log**
- AH01071: Got error 'PHP message: [AuthLDAP] User '' logging inPHP message: [AuthLDAP] Username not supplied: return false'				
Source: Apache error

- AH01071: Got error 'PHP message: [AuthLDAP] User 'testaccount' logging inPHP message: [AuthLDAP] about to do LDAP authenticationPHP message: [AuthLDAP] connect to LDAP serverPHP message: Array\n(\n [scheme] => ldaps\n [host] => ldap.nist.ac.th\n [user] => uid=wordpress,OU=WordPress,OU=_TurnOnMail,OU=SystemAccountdc=nist,dc=ac,dc=th\n [pass] => secret\n [path] => /OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th\n)\nPHP message: [AuthLDAP] LDAP authentication failed with exception: bind was not successfull: Can't contact LDAP server',		
Source: Apache error 

**3. Error when user login on WordPress login page**
- Unknown email address. Check again or try your username.

Do you have anything to advice or suggest? Thank you.

**Comment by heiglandreas** [comment]
Hey @phodchara. Thanks for reaching out.

 There are some things that immediately come to my mind:

* can the DNS-Name bve resolved on the webserver? I can not resolve `ldap.nist.ac.th` from my machine so if the web-server is running outside of a local network it might also have issues resolving that name.
* If the name can be resolved: Can you actually connect to the ldap-server from the webserver? Via CLI? If that is not possible due to firewall-rules, then you might need to adapt the network settings appropriately
* Have you tried adding the ldaps-port to the LDAP-URI? Like `...@ldap.nist.ac.th:636/...`?
* As it is an ldaps-connection: Is it secured with a self-signed certificate? That is always a PITA. There are some ways to get around that and I will need to add some config-flags enable that right from the plugin. As long as that is not fixed, check out [this README](https://github.com/heiglandreas/ldap_cert_test/blob/master/README.md) I wrote some time ago

Please do get back with your findings so that we can get that fixed.

**Comment by phodchara** [comment]
Hi Andreas,

This is an answer for your questio

1. For DNS-Name, Actual's nistldap.nist.ac.th
2. The connection via CLi work very well but still can't login with AD account. I guess the problem cause LDAP URI setting. On below's these URI that I use 

- ldap://uid=USERNAME,ou=WordPress,ou=_TurnOnMail,ou=SystemAccount,dc=nist,dc=ac,dc=th:PASSWORD@nistldap.nist.ac.th/ou=WordPress,ou=_TurnOnMail,ou=SystemAccount,dc=nist,dc=ac,dc=th
- ldap://uid=USERNAME,ou=WordPress,ou=_TurnOnMail,ou=SystemAccount,dc=nist,dc=ac,dc=th:PASSWORD@nistldap.nist.ac.th:389/ou=WordPress,ou=_TurnOnMail,ou=SystemAccount,dc=nist,dc=ac,dc=th
- ldap://uid=USERNAME,ou=WordPress,ou=_TurnOnMail,ou=SystemAccount,dc=nist,dc=ac,dc=th:PASSWORD@nistldap.nist.ac.th/dc=nist,dc=ac,dc=th
- ldap://uid=USERNAME,ou=WordPress,ou=_TurnOnMail,ou=SystemAccount,dc=nist,dc=ac,dc=th:PASSWORD@nistldap.nist.ac.th:389/dc=nist,dc=ac,dc=th
-ldaps://uid=USERNAME,OU=WordPress,OU=_TurnOnMail,OU=SystemAccountdc=nist,dc=ac,dc=th:PASSWORD@nistldap.nist.ac.th:636/OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th
- ldaps://uid=USERNAME,OU=WordPress,OU=_TurnOnMail,OU=SystemAccountdc=nist,dc=ac,dc=th:PASSWORD@nistldap.nist.ac.th/OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th
- ldap://USERNAME:PASSWORD@nistldap.nist.ac.th:389/DC=nist,DC=ac,DC=th
- ldap://USERNAME:PASSWORD@nistldap.nist.ac.th/DC=nist,DC=ac,DC=th
- ldap://USERNAME@nist.ac.th:PASSWORD@nistldap.nist.ac.th:389/DC=nist,DC=ac,DC=th
- ldap://USERNAME@nist.ac.th:PASSWORD@nistldap.nist.ac.th/DC=nist,DC=ac,DC=th


![LDAP](https://user-images.githubusercontent.com/55968695/104543879-150a3280-5659-11eb-9cd0-fe40509d138e.png)


Please advice, Thank you

**Comment by phodchara** [comment]
Additional information, Why I think the problem cause LDAP URI, because I try to use LDAP WP Login Integration With Active Directory plugin. User can login to the site.

Please advice, Thank you

**Comment by heiglandreas** [comment]
* did you encode possibly problematic characters in the password using URL-Encoding?
* What is the DN of the user with USERNAME? 'Cause if that is the WordPress-User from the screenshot then you would need to use this LDAP-URI: `ldap://cn=WordPress,OU=WordPress, OU=_TurnOnMail,OU=SystemAccount,DN=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th/OU=WordPress, OU=_TurnOnMail,OU=SystemAccount,DN=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th` (given that the users that shall log in via LDAP are located in the `OU=WordPress, OU=_TurnOnMail,OU=SystemAccount,DN=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th`-subtree)

Note the `cn` instead of the `uid`. You could also be using `samAccountName`.

**Comment by phodchara** [comment]
- did you encode possibly problematic characters in the password using URL-Encoding?
No

- What is the DN of the user with USERNAME?
Domain name's 'nist.ac.th'

- LDAP URI that i try
ldap://cn=USERNAME,OU=WordPress, OU=_TurnOnMail,OU=SystemAccount,DN=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th/OU=WordPress, OU=_TurnOnMail,OU=SystemAccount,DN=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th

ldap://cn=USERNAME,DN=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th/DN=nist,DC=ac,DC=th

ldap://samAccountName=USERNAME,DN=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th/DN=nist,DC=ac,DC=th

All of them them still doesn't work. Please advice.
Thank you

**Comment by heiglandreas** [comment]
DN is not the Domain Name but the Distinguished Name.

Have you URL-Encoded the password? For example by using something like https://www.urlencoder.org

**Comment by phodchara** [comment]
- This is DN for this user > cn=wordpress,OU=WordPress, OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th
- Not yet, because we don't encode anything.
- On below's LDAP URI that i try again

ldap://cn=WordPress,OU=WordPress, OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th/OU=WordPress, OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th

ldap://cn=wordpress,OU=WordPress, OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th/dc=nist,dc=ac,dc=th

**Comment by heiglandreas** [comment]
There is no need to send more LDAP-URIs until you use an URL-Encoded password.

Also provide the log file with the debuggin information from AuthLdap.

**Comment by phodchara** [comment]
Thank you so much for your reply.
For URL-Encoded the password, We don't use a special character in password . 
On below's the log from AuthLDAP

LDAP URI - ldap://CN=wordpress,OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th/OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th

Log
AH01071: Got error 'PHP message: [AuthLDAP] User '' logging inPHP message: [AuthLDAP] Username not supplied: return false'

AH01071: Got error 'PHP message: [AuthLDAP] User 'userwp' logging inPHP message: [AuthLDAP] about to do LDAP authenticationPHP message: [AuthLDAP] connect to LDAP serverPHP message: Array\n(\n [scheme] => ldap\n [host] => nistldap.nist.ac.th\n [user] => CN=wordpress,OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th\n [pass] => PASSWORD\n [path] => /OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th\n)\nPHP message: [AuthLDAP] No bind successfull. Exception thrown in line 70',

**Comment by heiglandreas** [comment]
Can you edit the file `authLdap.php` in the folder `wp-contents/plugins/authldap` and add the following line after line 282:

```php
authldap_debug(($result === true)?'true':'false');
```

After that please try to log in again and send the content of the error log again. Thanks

**Comment by phodchara** [comment]
This is an information. 
Edit authLdap.php > see picture
![AuthLDAP_Edit](https://user-images.githubusercontent.com/55968695/104693667-a30b1980-573c-11eb-863d-20aaeffc1019.png)

Log
AH01071: Got error 'PHP message: [AuthLDAP] User '' logging inPHP message: [AuthLDAP] Username not supplied: return false'	

AH01071: Got error 'PHP message: [AuthLDAP] User 'userwp' logging inPHP message: [AuthLDAP] about to do LDAP authenticationPHP message: [AuthLDAP] connect to LDAP serverPHP message: Array\n(\n [scheme] => ldap\n [host] => nistldap.nist.ac.th\n [user] => CN=wordpress,OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th\n [pass] => PASSWORD\n [path] => /OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th\n)\nPHP message: [AuthLDAP] falsePHP message: [AuthLDAP] No bind successfull. Exception thrown in line 70'


Thank you so much

**Comment by heiglandreas** [comment]
OK. This means that the main part of the LDAP-URI is correct as the main user can conenct to the LDAP-Server. 

But the authentication of the user is then not working.

Can you send me the LDAP-details of the user that you are trying to log in? Like the Distinguished name (DN) of that user? And what Attributes are you trying to match for that user? 

'Cause I could think that you are still using the default filter `(uid=%s)` which might not work as you probably need `(samAccountName=%s)` instead. And are the users that shall log into WordPress all part of the subtree `OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th`? Or are they part of a different subtree? Then that different subtree needs to be set as path in the LDAP-URI

**Comment by phodchara** [comment]
Hi Heiglandreas
This is the LDAP detail of the user that try to login > See picture
![AuthLDAP1](https://user-images.githubusercontent.com/55968695/104697013-af45a580-5741-11eb-9451-9d7e70cade5a.png)

And I have a good thing when change LDAP URI to below 
**ldap://CN=wordpress,OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th/DC=nist,DC=ac,DC=th**

and the default filter to **(samAccountName=%s)**

The error log seem better than the last time (see on below)

_AH01071: Got error 'PHP message: [AuthLDAP] User 'userwp' logging inPHP message: [AuthLDAP] about to do LDAP authenticationPHP message: [AuthLDAP] connect to LDAP serverPHP message: Array\n(\n [scheme] => ldap\n [host] => nistldap.nist.ac.th\n [user] => CN=wordpress,OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th\n [pass] => PASSWORD\n [path] => /DC=nist,DC=ac,DC=th\n)\nPHP message: [AuthLDAP] truePHP message: [AuthLDAP] LDAP authentication successfullPHP message: [AuthLDAP] could not get user attributes from LDAPPHP message: [AuthLDAP] Exception getting LDAP user: The user-ID attribute has not been returned',_

For OU, We have a lot OU under NIST domain.

Thank you so much

**Comment by heiglandreas** [comment]
Previously you described that these are your settings:

> Name-Attribute: name
> User-ID Attribute: uid
> Mail Attribute: mail
> Default Role: Subscriber

But if I read that correct so far the userID-Attribute is not `uid` but `samAccountName` 

Please check also the other fields to make sure everything is set up as necessary.

Additionally you can probably set the path to `OU=SystemAccount,DC=nist,DC=ac,DC=th` but if that doesn't work you can leave it as it is now.

**Comment by phodchara** [comment]
Hi  Heiglandreas

Good news, We got it!. The setting's 

1. LDAP URI: ldap://CN=wordpress,OU=WordPress,OU=_TurnOnMail,OU=SystemAccount,DC=nist,DC=ac,DC=th:PASSWORD@nistldap.nist.ac.th/DC=nist,DC=ac,DC=th
2. User-ID Attribute: samAccountName
3. The default filter: (samAccountName=%s)


Thank you so much for your help. I am appreciated the things you do so much indeed.
