### ISSUE TITLE
Version 2.4.3 is not packaged correctly

### ISSUE THREAD

**Issue by gramakri** [heiglandreas/authLdap#194]
There is something wrong with the new release. 

* https://github.com/heiglandreas/authLdap/releases/tag/2.4.3 was tagged from https://github.com/heiglandreas/authLdap/commit/f85560575b75a2f96e6fd6108a3ea4af362364d6 which does not belong to any branch on this repository, and may belong to a fork outside of the repository.
* VERSION file and authLdap.php are incorrect and still say 2.4.2 in the release tarballs. So when this latest release is installed, WP admin still says update is available to 2.4.3.

**Comment by heiglandreas** [comment]
Thanks for spotting! Will fux that tomorrow.

**Comment by gramakri** [comment]
On a unrelated note, would be nice if the release tarballs did not have the version number inside it. Currently, the have `authLdap-2.4.2` directory. When using WP CLI, wp plugin activate release.zip, it installs as directory `authLdap-2.4.2`. This messes up with WP's plugin update mechanism. It really wants the directory to be name "authldap"  (no version and all lower case) for the update to be reliable.

I am not an expert on all this, but the above was just an observation. @heiglandreas Do you have any suggestion for the above? What I do right now is rename the directory after wp plugin install and then wp plugin activate. It's a bit messy.

**Comment by heiglandreas** [comment]
The release zips are created by github automatically so I don't have any option in fixing that on my side.

**Comment by heiglandreas** [comment]
The version string should now be fixed with the new 2.4.6 release (which has no functionality changes, only changes in the way the deployment is handled. 

Thanks for bringing it to my attention. But you can also use the plugin-version from the WP plugin directory. It is exactly the same version as it gets deployed to the plugin directory as soon as there is a build created here. 

So the version you can download from https://downloads.wordpress.org/plugin/authldap.zip might be the better one for you ;-)

**Comment by gramakri** [comment]
@heiglandreas Ah, that's an excellent suggestion, thanks.

BTW, the VERSION file in https://github.com/heiglandreas/authLdap/releases/tag/2.4.6 is still 2.4.2. Is that file important?

**Comment by gramakri** [comment]
@heiglandreas Is the https://downloads.wordpress.org/plugin/authldap.zip something you upload manually? If so, do you think you can make those downloads as https://downloads.wordpress.org/plugin/authldap.<version>.zip ? The reason is that when making reproducible builds (like with a docker image), it's useful to be able to download/pin to the exact plugin version that we tested with.

**Comment by heiglandreas** [comment]
The VERSIOn file is completely irrelevant by now.

The zip file from wordpress. org is automatically created from the wordpress plugin repository. It's not something that I provide so here I also don't have any possibility to modify the path or name.

**Comment by gramakri** [comment]
@heiglandreas Thanks for clarifying? Maybe the VERSION file can be removed from the repo? In any case, I will close this issue now.
