### ISSUE TITLE
UI: make text fields wider to make longer field content visible

### ISSUE THREAD

**Issue by mdollinger** [heiglandreas/authLdap#195]
I love your tool, it was easy to install and activate, although i am no LDAP expert - thanks a lot.

Only thing i would change is the width of the config fields - they are too small for most of the values.
An LDAP URI value _ldap://uid=ldap,ou=bind,ou=ecg@localhost:30389/ou=ecg_ is not an extreme long text, but not even this is completely visible in the text field.
See also here, my group filter and the LDAP group mapping ( _wordpress_interactive_contributor_coordination_ ) is cut
![grafik](https://user-images.githubusercontent.com/9161977/106803905-f9e18000-6664-11eb-8f6d-df8939607d94.png)

A setting like this (and something equivalent for the mappings) would provide a feasible amount of space for most of the data:
.regular-text {
    width: 50em;
}

**Comment by heiglandreas** [comment]
Thanks for the suggestion! I'Ve jsut released version 2.4.8 which brings the text-fields to 100% width.

![image](https://user-images.githubusercontent.com/91998/106853089-6d14e180-66b9-11eb-8eca-d0c0cf8bd27c.png)

**Comment by mdollinger** [comment]
Wow, already solved ;)

Thank you
