### ISSUE TITLE
UI: group/role mapping: Avoid repeating tutorial text

### ISSUE THREAD

**Issue by mdollinger** [heiglandreas/authLdap#196]
Currently there are 3 lines of text after every group/role saying basically the same:
![grafik](https://user-images.githubusercontent.com/9161977/106859762-c8e46800-66c3-11eb-8c8c-e71ff2ea4653.png)

For a bigger amount of wp-roles this can harm the overview.
My suggestion is this:
![grafik](https://user-images.githubusercontent.com/9161977/106860718-0dbcce80-66c5-11eb-99a4-adbdf934f7e1.png)

**Comment by heiglandreas** [comment]
Good idea! Thanks! 

Can you create a PullRequest for that?

**Comment by mdollinger** [comment]
Wow, you are really fast ;)

But sorry, no, i have no idea about this.
For the screenshot i just did some HTML-manipulation locally in my browser.

The only help i can give is, that the width must be reduced again (ticket #195 ) to avoid a line break.

**Comment by heiglandreas** [comment]
:smile: Sometimes I'm fast.

Can you specify the issue with the width in #195 a bit more in detail? And possibly reopen it?

And I'll see to rearranging the stuff here :wink:

**Comment by heiglandreas** [comment]
How does this look like?

![image](https://user-images.githubusercontent.com/91998/106870537-82960580-66d1-11eb-9241-e85e64a15d93.png)

It's included with v2.4.9 ;-)

**Comment by mdollinger** [comment]
Remove duplicate text: 100 % happyness

Regarding "shall match to" - see how it looks in my case.
As soon the role names are a bit longer, line breaks occur.
Also we carefully named our roles to clearly reveal their hierarchy:

- Contributor 
- Contributor_accreditation 
- Contributor_coordination 

This is lost with align right:
![grafik](https://user-images.githubusercontent.com/9161977/106909533-ac1a5580-6700-11eb-9c3a-2ec43f4c780d.png)

My proposal would be to 
- either put the "shall match to" in a separate <td>
- or add it to the <td> with the <input> tag
(but here you would need to reduce the width eg. to 80% to avoid line break here)

**Comment by heiglandreas** [comment]
Does this look better?

![image](https://user-images.githubusercontent.com/91998/106996979-440c5380-6782-11eb-9f90-c2c7e2b7be5a.png)

**Comment by mdollinger** [comment]
Das ist nicht nur *better*, das ist *perfect* ;)

**Comment by heiglandreas** [comment]
The modification has also been released, so I can close this.
