### ISSUE TITLE
Password in env variable does not work?

### ISSUE THREAD

**Issue by gandru2** [heiglandreas/authLdap#206]
Connecting wordpress 5.8.2 with openldap.

**Description**
I can make it work if i specify the password in clear in the ldap uri like
ldap://cn=myuser:mypassword@ldap.example.com/dc=com

I can not make it work if i want to hide the password and load it from an environment variable

**Comment**
In the extension page
"""
 You can also provide different parts of the LDP-URI from environment variables by providing %env:[VARIABLENAME]% within your LDAP-URI. So if you want to provide the password from an Environment-variable LDAP_PASSWORD your LDAP-URI looks like ldap://uid=adminuser,dc=example,c=com:%env:LDAP_PASSWORD%@ldap.example.com/dc=basePath,dc=example,c=com 
"""
this looks confusing to me as it says 
%env:[VARIABLENAME]%
but example says
%env:LDAP_PASSWORD%

should ww have to specify [ ]  characters ?

**Steps**

1- in wp-config.php file, adding new line
define( 'LDAP_PASSWORD',    'mypassword' );

2- restart apache

3- in wordpress ldapauth extension page, trying

ldap://cn=myuser:%env:LDAP_PASSWORD%@ldap.example.com/dc=com
ldap://cn=myuser:%env:[LDAP_PASSWORD]%@ldap.example.com/dc=com

break wordpress in login page

ldap://cn=myuser:%LDAP_PASSWORD%@ldap.example.com/dc=com

returns incorrect password

any helps ?
thanks

**Comment by heiglandreas** [comment]
Using `define('LDAP_PASSWORD', 'mypassword');` does not define an environment variable but a PHP-Internal variable.

Environment variables are usually defined outside the PHP-context. YOu can for example define them within your webservers configuration for the PHP environment.

But you can also use `putenv('LDAP_PASSWORD=mypassword');` within wp-config.php.

The confusion that you had comes from the fact that the string "LDAP_PASSWORD" is not fixed. You can use any string you like for that. The only relevant thing is that the string you use within the `putenv` needs to be the same as you use after the `env:` in the LDAP-URI. So when you use `putenv('FOOB=myldappassword');` then your ldapURI needs to contain `%env:FOOB%` to make use of that.

Does that shed some light?

**Comment by gandru2** [comment]
amazing, thank you very for the explanation, using 

> putenv('LDAP_PASSWORD=mypassword'); 

in wp-config.php does solve my problem
