### ISSUE TITLE
Read profile picture from LDAP

### ISSUE THREAD

**Issue by Samonitari** [heiglandreas/authLdap#210]
Hi,

It would be nice to have to load the users' profile picture from LDAP to Wordpress.
As a little justification, besides the name, profile picture **is?** the second most important info people would use to identify authors for example. I am not discontent, but maybe it would add a significant plus to the plugin's perceived value.

The `inetOrgPerson` objectClass (which is not rare as a structural objectClass for members/users I think) has the `jpegPhoto` attribute.
OTOH MS-AD has the thumbnailPhoto attribute. 
Maybe make it configurabe: profile picture attribute could be set on authLDAP settings page.
Not existing given attribute should be handled well, as the given attribute - as far as inetOrgPerson::jpegPhoto (which could contain PNG I think :smile: ) goes - is optional.

Thank for your work!

**Comment by Samonitari** [comment]
Wow, I never realized Wordpress is such a crap - well I knew that it in in general, the profile image handling nonsense is new to me.
I assumed everybody could set his/her own. Maybe a plugin to download/access from some service.
Turns out, Gravatar is **THE** default source, and you **need a plugin to load user pictures from files***. Just, I don't know, wow.

So by itself, this plugin cannot solve this.
I found [One User Avatar](https://wordpress.org/plugins/one-user-avatar/) as a promising plugin (doesn't do anything unnecessary, just avatars, but it has some good configuration options for that).

So this plugin would need to check for jpegPhoto attr (on user creation and whenever it refreshes users' attrs), download to some specific folder (under uploads?) if: there is stored jpegPhoto in LDAP, but WP user doesn't yet have it OR user 's stored jpegPhoto's hash differs from the current jpegPhoto's hash. Or something like that, and that is just half of the problem

**Comment by heiglandreas** [comment]
Yeah. There was a reason why I didn't tackle this. As I know that [I dabbled around with that](https://stackoverflow.com/questions/16937863/display-thumbnailphoto-from-active-directory-in-php/16948219#16948219) some years back. 

But your plugin would need to in essence use a filter that modifies the URL for the avatar and replace the gravatar one with a `data:` link with the content of the `jpegPhoto` attribute.

And that was too much for the plugin.

As I still want to do a complete rewrite of this plugin to allow more interaction with other plugins it should then be possible to retrieve more informations from the LDAP and then do stuff with that queried information.

But that is perhaps for this year on my agenda.... perhaps not :-/
