### ISSUE TITLE
PHP 8.12 compatibility

### ISSUE THREAD

**Issue by smallouki** [heiglandreas/authLdap#211]
It seems I've stumbled upon an issue with the php version 8.12. The ldap plugin does not work and in the log there is an error message: 

"no resource handle given" 

After reverting to php 8.0.15 I could log in again using your plugin.

Thanks for the great work.

**Comment by heiglandreas** [comment]
Oh. Right. THanks for mentioning this! There was a change in what the LDAP-commands return. And I am checking that at one point! Expect a fix next week!

**Comment by smallouki** [comment]
Wow. You are indeed as good as your reputation indicates. Thanks a lot!

**Comment by smallouki** [comment]
Awesome thank you very much. I'll try asap.
