### ISSUE TITLE
enable multiple group 

### ISSUE THREAD

**Issue by matbr** [heiglandreas/authLdap#219]
Hi Andreas, 

we're moving forward with our project to production and would need to switch from Karonlinas fork back to the main version of your plugin. 

Is there anything to support to get the multiple group mapping [https://github.com/heiglandreas/authLdap/pull/200] into the master? 

Please let us know how to support...!

best, 

Mat

**Comment by heiglandreas** [comment]
This should now (since version 2.5.4) be working out of the box after configuring it accordingly.
