### ISSUE TITLE
Allow group-mapping to be optional

### ISSUE THREAD

**Issue by heiglandreas** [heiglandreas/authLdap#22]
Currently, the plugin requires LDAP group membership to login.  In our install I have disabled that functionality by commenting out the required code in authLdap.php.

I'd like to see an option to enable/disable the use of groups for assigning roles.

**Comment by chaplina** [comment]
As you mentioned in your email, if using groups for roles is not used, you'll need another option to specify the role to be assigned to new users.

**Comment by heiglandreas** [comment]
So 
 * **EITHER** assign a new users role according to the LDAP-group membership (current behaviour)
 * **OR** assign **all** new users to **the same** given role (new feature)

**Comment by heiglandreas** [comment]
This has just been implemented with PR #24 

You can leave all LDAP-Groups empty and just set a default role which will then be assigned to all users loging in.

**Comment by chaplina** [comment]
Ideally, the LDAP query to search for groups would be "disabled" with this option (why waste a connection to LDAP if the query results will not be used).

**Comment by heiglandreas** [comment]
OK. That would then be an extra option to that **Don't check LDAP-Groups at all and go straight to the default group**. Thanks for the input!

**Comment by heiglandreas** [comment]
This has been implemented by @EmTeedee in #26
