### ISSUE TITLE
AuthLDAP seems to break user roles / resets to Editor role when WooCommerce plugin is involved

### ISSUE THREAD

**Issue by d19dotca** [heiglandreas/authLdap#221]
Hello,

I've been doing a lot of digging (please [refer to this forum post here](https://forum.cloudron.io/topic/6625/logging-in-resets-role-to-editor-instead-of-administrator-or-shop-manager/) where I did a lot of troubleshooting), and it appears that the latest update (2.5.1) of AuthLDAP breaks down when the WooCommerce plugin is enabled on the site. 

I manage roughly 20+ WordPress sites with the AuthLDAP plugin enabled, and after updating to v2.5.1 of the plugin, users (including myself as an administrator) had their roles reset to "Editor" which is the default role for new user logins but only when WooCommerce was enabled on the site - all others worked fine. 

It seems that the plugin failed to recognize a role despite it existing in the database on each user and in a way that is no different from the other sites as best I can tell. The only sites I had issues with are the ones where WooCommerce was enabled, all other sites worked fine after the plugin update.

I suspect this has something to do with this PR that was added in the latest version but am not 100% certain of that: https://github.com/heiglandreas/authLdap/pull/209/files

Your help would be greatly appreciated so I can get to updating this plugin on my WooCommerce sites. For now, the workaround was to simply restore AuthLDAP to the previous version which works fine. Some quick references from the other post that may be helpful:

**Working site:**
mysql> SELECT meta_key, meta_value FROM wp_usermeta WHERE meta_key = 'wp_capabilities';
+-----------------+---------------------------------+
| meta_key        | meta_value                      |
+-----------------+---------------------------------+
| wp_capabilities | a:1:{s:13:"administrator";b:1;} |
+-----------------+---------------------------------+
1 row in set (0.00 sec)

**Non-working site:**
mysql> SELECT meta_key, meta_value FROM wp_usermeta WHERE meta_key = 'wp_capabilities';
+-----------------+---------------------------------+
| meta_key        | meta_value                      |
+-----------------+---------------------------------+
| wp_capabilities | a:1:{s:13:"administrator";b:1;} |
| wp_capabilities | a:1:{s:8:"customer";b:1;}       |
| wp_capabilities | a:1:{s:12:"shop_manager";b:1;}  |
| wp_capabilities | a:1:{s:8:"customer";b:1;}       |
| wp_capabilities | a:1:{s:8:"customer";b:1;}       |
| wp_capabilities | a:1:{s:8:"customer";b:1;}       |
| wp_capabilities | a:1:{s:8:"customer";b:1;}       |
| wp_capabilities | a:1:{s:8:"customer";b:1;}       |
| wp_capabilities | a:1:{s:8:"customer";b:1;}       |
+-----------------+---------------------------------+
9 rows in set (0.00 sec)

Note the administrator role at top of both is my account, and the value seems identical in them.

The  ```wp --format=json option get authLDAPOptions``` command provided me with this output as well for the configuration of the AuthLDAP plugin, FYI:

```
{
	"Enabled": "1",
	"CachePW": false,
	"URI": "ldap:\/\/172.18.0.1:3002\/ou=users,dc=cloudron",
	"Filter": "(username=%s)",
	"NameAttr": "givenName",
	"SecName": "sn",
	"UidAttr": "username",
	"MailAttr": "mail",
	"WebAttr": "",
	"Debug": "1",
	"DefaultRole": "editor",
	"GroupEnable": false,
	"GroupOverUser": false,
	"Version": 1,
	"URISeparator": "",
	"StartTLS": false,
	"Groups": {
		"administrator": "",
		"editor": "",
		"author": "",
		"contributor": "",
		"subscriber": "",
		"customer": "",
		"shop_manager": ""
	},
	"GroupSeparator": "",
	"GroupBase": "",
	"GroupAttr": "",
	"GroupFilter": "",
	"DoNotOverwriteNonLdapUsers": false
}
```

For logs, I see the following before an update to v2.5.1:

```
Mar 19 17:27:15 [Sun Mar 20 00:27:15.727930 2022] [php7:notice] [pid 652] [client 207.216.93.172:46612] [AuthLDAP] User ‘<username>’ logging in, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:15 [Sun Mar 20 00:27:15.727985 2022] [php7:notice] [pid 652] [client 207.216.93.172:46612] [AuthLDAP] about to do LDAP authentication, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:15 [Sun Mar 20 00:27:15.727992 2022] [php7:notice] [pid 652] [client 207.216.93.172:46612] [AuthLDAP] connect to LDAP server, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:15 [Sun Mar 20 00:27:15.913285 2022] [php7:notice] [pid 652] [client 207.216.93.172:46612] [AuthLDAP] LDAP authentication successfull, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:15 [Sun Mar 20 00:27:15.922068 2022] [php7:notice] [pid 652] [client 207.216.93.172:46612] [AuthLDAP] Existing user, uid = 2, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:15 [Sun Mar 20 00:27:15.922741 2022] [php7:notice] [pid 652] [client 207.216.93.172:46612] [AuthLDAP] Existing user's role: administrator, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:15 [Sun Mar 20 00:27:15.923002 2022] [php7:notice] [pid 652] [client 207.216.93.172:46612] [AuthLDAP] The LDAP user has an entry in the WP-Database, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:15 [Sun Mar 20 00:27:15.948548 2022] [php7:notice] [pid 652] [client 207.216.93.172:46612] [AuthLDAP] user id = 2, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
```

After updating to v.2.5.1, notice the role is not recognized and essentially resets to Editor:

```
Mar 19 17:27:54 [Sun Mar 20 00:27:54.153389 2022] [php7:notice] [pid 652] [client 207.216.93.172:47482] [AuthLDAP] User ‘<username>’ logging in, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:54 [Sun Mar 20 00:27:54.153441 2022] [php7:notice] [pid 652] [client 207.216.93.172:47482] [AuthLDAP] about to do LDAP authentication, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:54 [Sun Mar 20 00:27:54.153454 2022] [php7:notice] [pid 652] [client 207.216.93.172:47482] [AuthLDAP] connect to LDAP server, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:54 [Sun Mar 20 00:27:54.309505 2022] [php7:notice] [pid 652] [client 207.216.93.172:47482] [AuthLDAP] LDAP authentication successfull, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:54 [Sun Mar 20 00:27:54.319895 2022] [php7:notice] [pid 652] [client 207.216.93.172:47482] [AuthLDAP] Existing user, uid = 2, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:54 [Sun Mar 20 00:27:54.320231 2022] [php7:notice] [pid 652] [client 207.216.93.172:47482] [AuthLDAP] Existing user's role: , referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:54 [Sun Mar 20 00:27:54.320249 2022] [php7:notice] [pid 652] [client 207.216.93.172:47482] [AuthLDAP] no role yet, set default role, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:54 [Sun Mar 20 00:27:54.320445 2022] [php7:notice] [pid 652] [client 207.216.93.172:47482] [AuthLDAP] The LDAP user has an entry in the WP-Database, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
Mar 19 17:27:54 [Sun Mar 20 00:27:54.346697 2022] [php7:notice] [pid 652] [client 207.216.93.172:47482] [AuthLDAP] user id = 2, referer: https://<hostname>/wp-login.php?loggedout=true&wp_lang=en_CA
```

**Comment by jimcavoli** [comment]
I've also observed these issues with a nearly identical configuration to @d19dotca

**Comment by heiglandreas** [comment]
Thank you for this amazing and excessive bug-description! I'm digging into this right now!

**Comment by heiglandreas** [comment]
It looks like the culprit is here WooCommerce and espechially the function [wc_modify_editable_roles](https://plugins.trac.wordpress.org/browser/woocommerce/trunk/includes/wc-user-functions.php#L497) which modifies the roles that can be edited. It looks like we do not have a match between the capabilities and the result of filtering the editable roles. Which means there is no possible role for the user anymore.

But I am thinking about skipping the filtering step as this is not one user assigning another user a role but the system checking what roles are available. So expect a fix to this soonish.

**Comment by heiglandreas** [comment]
The new version has been pusehd to the WordPress plugin directory. THis issue should be fixed in there. Thanks for reporting and for your patience!

**Comment by fbartels** [comment]
I can confirm that after updating the ldap plugin the user role is no longer set to editor after login.

**Comment by d19dotca** [comment]
Like @fbartels, I have tested this evening and it appears to be working correctly now. Thanks so much @heiglandreas! :-)

**Comment by heiglandreas** [comment]
Thanks for the feedback! I consider this as solved then :tada:
