### ISSUE TITLE
Multisite Support

### ISSUE THREAD

**Issue by 709398summer** [heiglandreas/authLdap#223]
Does the latest release support multisite? If so, how can I assign user to a site.  I am getting the following error: 

Error: The username summer is not registered on this site. If you are unsure of your username, try your email address instead.

authLDAP debug shows LDAP binding and login as successful.

**Comment by heiglandreas** [comment]
Sorry for letting this hang loose for so long. I assume you did get an authentication for multisite sorted. 

In general this plugin should support multisite but so if you are still interested in a solution feel free to reopen this issue.
