### ISSUE TITLE
The User-ID attribute has not been returned 

### ISSUE THREAD

**Issue by mikibarzilay** [heiglandreas/authLdap#226]
Dear colleagues,
I'm facing an issue with authLDAP on WordPress ver. 5.9.3 running on Linux (RHEL 8.3) and PHP 8 (REMI) using php80-php-ldap-8.0.20-1.el8.remi.x86_64. My LDAP based on Windows Active Directory.

I'm unable to login to WP, in debug log I'm receiving: Exception getting LDAP user: The User-ID attribute has not been returned.

I'm able to execute the same LDAP filter on Windows PowerShell
I'm attaching screenshot with my configuration.

I tried the situation both with WP user exists and non-exist.

I'm going to appreciate any advise.

Micky
![2022-06-29_02-09](https://user-images.githubusercontent.com/10675448/176369671-884cc896-fd8b-4732-8153-d5fdffca191d.png)
![2022-06-29_02-06](https://user-images.githubusercontent.com/10675448/176369681-aec59768-79aa-47df-acd2-983f1c56adb6.png)
![2022-06-29_02-04](https://user-images.githubusercontent.com/10675448/176369688-daec3303-ff62-45ca-84aa-3189165f3d1e.png)

**Comment by heiglandreas** [comment]
Hey there.

Thanks for reaching out.

Two questions though to understand better what's going on:

* Did it work previously or is that a new issue?
* Did you install the extension from the plugin-directory or from github master?

What I recognize though immediately - though I'm not sure that's the cause of the issue - is that the attribute usually is written `samAccountName` with a lower-case 's'. That shouldn't cause an issue as LDAP-attributes should be case-insensitive, though... 😕

Ah no.

what have you configured as User-ID attribute? By default that is `uid` but your LDAP does not provide such an attribute. You might want to overwrite that with `samAccountName` instead.

**Comment by mikibarzilay** [comment]
Hey,
Thank you for your quickly response.
It's the first time I'm using the plugin on a new WordPress (Multisite) installation.

I have manually downloaded the plugin from the WordPress Plugins site (not GitHub) and install it.

About samAccountName, I executed the same filter in PowerShell and copied the SamAccoutName returned properties.

Thanks
Micky

**Comment by heiglandreas** [comment]
Yeah. The casing shouldn't be the issue. I rather think it's the config of the "Settings for creating new users"

![image](https://user-images.githubusercontent.com/91998/176374314-505b7283-d970-4a44-937b-10b4a7e4170e.png)

The default values are based on an OpenLDAP, but as you are using an ActiveDirectory you will need to adapt this mapping.

For more information check out https://andreas.heigl.org/2010/08/22/authldap/

**Comment by mikibarzilay** [comment]
Thank you for your response.
I forgot to upload a screenshot of "Settings fpr creating new Users" section. 
Herein attached.

Please advise.
Thank you for your support

Micky

![image001](https://user-images.githubusercontent.com/10675448/176418657-832bf618-c911-4655-a755-9b666802b08b.png)

**Comment by mikibarzilay** [comment]
Thank you.
It's working with SamAccount in the USer-ID Attribute field.

Thank you so much.
Micky

**Comment by heiglandreas** [comment]
Thought so :wink: 

Have fun!
