### ISSUE TITLE
Strong password - LDAP authentication failed

### ISSUE THREAD

**Issue by mikibarzilay** [heiglandreas/authLdap#227]
Hello,
In case I'm using a simple alphanumeric 8 characters password the authLdap is working well and users are able to login with their Active Directory user & password.

However, when I'm trying to use a strong and complex 25 characters password, that includes also special characters, the debug shows: "LDAP authentication failed with exception: bind was not successful: Invalid credentials"

I tried to avoid special characters such ( ) , ; & * @, however the credential still fail.

Please advise.
Micky Barzilay

**Comment by heiglandreas** [comment]
Great to hear that you got it working.

I'll then close this.
