### ISSUE TITLE
Issue with Group Filter

### ISSUE THREAD

**Issue by DonSYS91** [heiglandreas/authLdap#231]
Hello, I need help with the group filter, right now the auth for an LDAP user along the attribute mapping are working flawlessly but not the group filter.

Environment:
WordPress: 6.1.1
PHP: 8.2
AuthLDAP: 2.5.3

LDAP User: wpuser
LDAP Group: websiteadmins

Executing the following ldapsearch command:
```ldapsearch -LLL -x -D "cn=wordpress,ou=sa,dc=example,dc=com" -w "Password" -H ldap://ldap.example.com:389 -b "dc=example,dc=com" -ZZ "(&(objectClass=groupOfNames)(member=uid=wpuser,ou=people,dc=example,dc=com))" "*"```

Will return:
```
dn: cn=websiteadmins,ou=groups,dc=example,dc=com
objectClass: groupOfNames
objectClass: gosaGroupOfNames
gosaGroupObjects: [U]
cn: websiteadmins
description:: REDACTED
member: uid=wpuser,ou=people,dc=example,dc=com
```

So the given LDAPsearch is returning successfully the groups for that given DN. 

Now on AuthLDAP plugins. I have the following settings:
```
Group-Base = dc=example,dc=com
Group-Attribute = cn
Group-Filter = (&(objectClass=groupOfNames)(member=%dn%))
```
But checking the debug logs the LDAP groups array is empty.

here is the debug logs:

```
[AuthLDAP] Group Filter: "(&(objectClass=groupOfNames)(member=uid=wpuser,ou=people,dc=example,dc=com))"
[AuthLDAP] Group Base: dc=example,dc=com
[AuthLDAP] LDAP groups: []
[AuthLDAP] Role from LDAP group:
[AuthLDAP] role from group mapping:
[AuthLDAP] no role yet, set default role
[AuthLDAP] The LDAP user has an entry in the WP-Database
[AuthLDAP] user id = 8
```

Any idea why the LDAP groups is failing to pull the groups?

Thanks in Advance!

**Comment by heiglandreas** [comment]
Can you add the following line of code in line 624 of the file `authLdap.php` (right before the `} catch (Exception $e) {`) and then try the authentication again and post the result here? That would be really helpful to solve this and figure out where something is going south...

**Comment by DonSYS91** [comment]
Thanks for the quick reply @heiglandreas 
This returned nothing sadly:
```
Found Groups: {"count":0}
```
I will try to use that debug line higher in the code to see if I can tackle it directly after the ldap search query.

**Comment by DonSYS91** [comment]
Hi @heiglandreas, solved, pretty stupid mistake on my end as I had the "User Read" option on so that user was trying to be used to for group mapping rather than the user with the required permissions within the base DN.
