### ISSUE TITLE
A fork working with wordpress 6.3

### ISSUE THREAD

**Issue by boutmos** [heiglandreas/authLdap#232]
Is there any fork for new and futur news  wordpress version ?

Thank you

**Comment by heiglandreas** [comment]
Why do a fork? What's the problem?

If you could specify what the issue is, I would be able to fix it...

**Comment by boutmos** [comment]
I have no problem, but It is still write "Compatible with wordpress 5.9" on the plugin store. So I thought the plugin was abandoned.

**Comment by heiglandreas** [comment]
The plugin is feature complete, so I only do updatrs when fixing something. But you are right: I could update that one 😁 Thanks for the hint

**Comment by boutmos** [comment]
Tahnx for your work :)

**Comment by heiglandreas** [comment]
New version is now mentioning that this is working with 6.3 as well. Thanks for the hint again :grin:

**Comment by boutmos** [comment]
Hi there is a problem when updating. I use Ansible with this task : `wp plugin update --all --allow-root --path=/var/www/html`, authLDAP is disabled and said : 
`L’extension authLdap/authLdap.php a été désactivée en raison d’une erreur : Le fichier de l’extension n’existe pas.` 
In english :
`The extension authLdap/authLdap.php has been disabled due to an error: The extension file does not exist.`
The file is existing and permissions are right.
To fix it, I reboot all my Virtual Machines and enabled your plugin then the error no longer appears.
Still working, thanx for updating 6.3 compatible in wordpress store :)

**Comment by heiglandreas** [comment]
where does the `authLdap` come from? As that should probably be `authldap` (note the lower case `l`)

Depending on the filesystem that can be rather picky....

But I am anyhow in the process of seting up automated testing for the latest wp version and might just use the wp-cli for that and that should then catch that issue.

Thanks for the hint!

**Comment by boutmos** [comment]
;)
