### ISSUE TITLE
blanks in values like ldap uri, username (cn)

### ISSUE THREAD

**Issue by sebastianpein** [heiglandreas/authLdap#243]
hi there,

first of all thanks a lot andreas for your work on this wp plugin!

i am having a hard time figuring out how to set the correct values for our environment. we are using active directory. therefore usernames (full path) are defined in the cn attribute. in our actual case, usernames (cn) as well as container names - the ou's where users and groups are located - might contain blanks (eg "cn=My Common Name" or "ou=My OU").

so the question is: how do i put those blanks into the strings of the plugin configuration?

enabling debugging, it seems like strings containing white space are being cut at the position of the whitespace, and then of course dont work. replacing " " with "%20" does not work either. prepending whitespace with "\" also does not work.

we cannot change the ldap values, so i need to figure out a way to have blanks in the configuration.

thank you for any thoughts!

best
sebastian

**Comment by heiglandreas** [comment]
Hey Sebastian.

Thanks for getting into contact.

What I am right now not understanding is where you are trying to insert those blanks. Is that in the LDAP-URI? Or somewhere else?

PErhaps a screenshot of the configuration you are currently trying with the spaces marked would help me a lot.

**Comment by sebastianpein** [comment]
hi andreas. thank you for your quick response!

yes, we are talking about the ldap-uri field.

i would like to enter something like "ldaps://cn=my username,ou=my ou,dc=org,dc=tld:mypasswd@1.2.3.4/ou=my ou,dc=org,dc=tld/".

probably the same issue will come up when taking group/role mapping into the picture. but thats only a required feature further down the road.

i am not with my notebook right now, so if the example is not good enough, i will post a screnshot later on.

thanks again for your efforts!

sebastian

**Comment by heiglandreas** [comment]
That's weird... As in essence the URL should be ... well, URLencoded :see_no_evil: 

So `ldaps://cn=my%20username,ou=my%20ou,dc=org,dc=tld:myPassword@1.2.3.4/ou=my%20ou,dc=org,dc=tld/` should work.....

Make sure that **all** special characters are encoded propperly. You can also use URLencoding for special characters in the Password!

**Comment by sebastianpein** [comment]
yeah, thats what i was thinking :D

all right. i will double and triple check. perhabs i just did something wrong.

i will check today and post back my findings.

thanks a lot!
sebastian

**Comment by heiglandreas** [comment]
And I'll also check whether it works that way or not. Will also post my findings :wink:

**Comment by sebastianpein** [comment]
i see...

so i encoded "=" as well. and that works. the string is now like this:

`ldaps://CN%3DMy%20CommonName%2COU%3DBenutzer%2COU%3DMy%20OU%2CDC%3Dorg%2CDC%3Dtld:P4ssW0rd@ldaps.server.tld/DC=org,DC=tld
`
![image](https://github.com/heiglandreas/authLdap/assets/8200452/082e44ca-1999-484c-9bad-77195991b91d)

**Comment by sebastianpein** [comment]
thanks again andreas. it's all working now.
