### ISSUE TITLE
No bind successfull. Exception thrown in line 75

### ISSUE THREAD

**Issue by Kvoo** [heiglandreas/authLdap#245]
Hiya.

Forgive me, I'm a total Wordpress/PHP noob.

To Preface: I'm working on a Windows Server, Wordpress is self-hosted for a company Intranet.

I'm trying to set up the Plugin to Authenticate against Active Directory. I specified all the necessary settings and tried to login with an LDAP user, but just got the default Wordpress "Wrong Password/Username" message.

I checked the php8.2 log and saw the following:
`[21-Nov-2023 08:23:33 UTC] [AuthLDAP] User 'xxxx' logging in
[21-Nov-2023 08:23:33 UTC] [AuthLDAP] about to do LDAP authentication
[21-Nov-2023 08:23:33 UTC] [AuthLDAP] connect to LDAP server
[21-Nov-2023 08:23:33 UTC] [AuthLDAP] No bind successfull. Exception thrown in line 75`

Now I'm not sure what the cause of this is, as the error isn't very verbose. This was with the Debug checkbox activated.

Now, in the src directory of the plugin I do see LdapList.php, LdapUri.php and some .php files for Exceptions, but when do these actually get used? No exception was thrown anywhere except in the PHP Log. Isn't there a function in the plugin to test the LDAP URI and Bind?

A bit of googling led me to the ldapsearch tool, however we're Windows Server only and I couldn't find an equivalent tool for Windows. Any help?

**Comment by Kvoo** [comment]
Nevermind, I got it to work :)

**Comment by irdet2** [comment]
@Kvoo do you mind explain a little bit more of how you managed to solve this one since I am having the same issue.

Looking forward for your answer.
