### ISSUE TITLE
LDAPS fails when LDAP works

### ISSUE THREAD

**Issue by bvarick** [heiglandreas/authLdap#248]
I'm trying to authenticate using LDAPS, and it fails. The log says:
`LDAP authentication failed with exception: bind was not successfull: Can't contact LDAP server, referer: https://wordpress.camp-wi.org/wp-login.php`

I am able to successfully login with LDAP, and I'm able to use LDAPS from other services.
Its not using a self-signed certificate, as I've tested with: `openssl s_client -connect <url>:636 -showcerts`

Any suggestions? Thanks!

**Comment by heiglandreas** [comment]
Hey there. Mind to post a (sanitized) screenshop of your authLdap config? Feel free to send it to authldap <at> heigl <dot> org if you do not want to post it here.

I do have an idea but need a confirmation

**Comment by bvarick** [comment]
Thanks! I'm sending you an email now

**Comment by heiglandreas** [comment]
It's been TLS.

Downloading the Root-certificate of the certificate chain to a known location `/path/to/cert.pem` and then adding 

```
TLS_CACERT /path/to/cert.pem
```

to the file `/etc/ldap/ldap.conf` should do the trick.

**Comment by bvarick** [comment]
Thanks so much for the help, that worked perfectly! Here's my new dockerfile for anyone else having this issue:
```
FROM wordpress

RUN set -x \
    && apt-get update \
    && apt-get install -y libldap2-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
    && docker-php-ext-install ldap \
    && apt-get purge -y --auto-remove libldap2-dev

RUN curl -L -o /etc/ssl/LEca.pem https://letsencrypt.org/certs/isrgrootx1.pem && \
    mkdir /etc/ldap && \
    echo "TLS_CACERT /etc/ssl/LEca.pem" >> /etc/ldap/ldap.conf

```
This downloads the Let's Encrypt cert, because that is what I'm using on the ldap server
