### ISSUE TITLE
Need help with Configuration

### ISSUE THREAD

**Issue by Philicoco** [heiglandreas/authLdap#249]
Hello, I have tried to set up authLDAP but unfortunately I cannot connect to the Ldap server

LDAP URI: 
ldap://uid=username,cn=users,dc=company,dc=com:password@192.168.x.x/dc=company,dc=com
 
Debug is switched on unfortunately I cannot find Authdebug.log

Error Log:
>[php:warn] [pid 78400] [client 192.168.x.x:62876] PHP Warning:  ldap_bind(): Unable to bind to server: Invalid DN syntax in /var/www/html/wp-content/plu>
 [php:notice] [pid 78400] [client 192.168.x.x:62876] [AuthLDAP] LDAP authentication failed with exception: bind was not successfull: Invalid DN syntax, r>
 [php:notice] [pid 78236] [client 192.168.x.x:62881] [AuthLDAP] User '' logging in
 [php:notice] [pid 78236] [client 192.168.x.x:62881] [AuthLDAP] Username not supplied: return false
 [php:notice] [pid 78239] [client 192.168.x.x:62906] [AuthLDAP] User 'test' logging in, referer: http://192.168.x.x/wp-login.php
[php:notice] [pid 78239] [client 192.168.x.x:62906] [AuthLDAP] about to do LDAP authentication, referer: http://192.168.x.x/wp-login.php
 [php:notice] [pid 78239] [client 192.168.x.x:62906] [AuthLDAP] connect to LDAP server, referer: http://192.168.x.x/wp-login.php
 [php:warn] [pid 78239] [client 192.168.x.x:62906] PHP Warning:  ldap_bind(): Unable to bind to server: Invalid DN syntax in /var/www/html/wp-content/plu><

**Comment by heiglandreas** [comment]
Hey there.

Thanks for getting in contact. Could you provide me with the actual LDAP-URI? (replace sensitive data with `x` but please leave in special characters if that is possible)

As the error hints towards a problem with the DN syntax I suspect the part between the `ldap://` and the `:password` to be the culprit.

If you do not want to post it here, feel free to send me an encrypted email to andreas [at] heigl [dot] org - find a GPG key at https://andreas.heigl.org/publickey/

**Comment by Philicoco** [comment]
Thanks for the replay her the URI is used
ldap://uid=logosldap,cn=users,dc=logos-gleisdorf,dc=at:Password@192.168.53.15/dc=logos-gleisdorf,dc=at

**Comment by heiglandreas** [comment]
At first sight that doesn't look suspicious.

Could you perhaps also provide the remaining config? Screenshots should be OK

**Comment by Philicoco** [comment]
Hello I have found the problem it now has a connection to the server. 
After I set "Do not authenticate existing WordPress-Users"
 I was also able to log in via ldap 
THX :)
