### ISSUE TITLE
Unable to redirect correctly

### ISSUE THREAD

**Issue by pbbunny** [heiglandreas/authLdap#30]
Debug is showing the following after a successful ldap login:

[Wed Mar 11 11:45:28 2015] [error] [client 1.1.1.1] PHP Catchable fatal error:  Object of class WP_Error could not be converted to string in /wordpress/wp-content/plugins/authldap/authLdap.php on line 332, referer: https://prdwp01.philasd.org/wp-login.php?redirect_to=https%3A%2F%2Fprdwp01.philasd.org%2Fwp-admin%2Fuser%2F&reauth=1

Version is 1.4.2

**Comment by pbbunny** [comment]
This seems to be related to #20.  The user's email address is registered already and so instead of giving an error message or something similar, it gives a blank page.

**Comment by chaplina** [comment]
My PHP is rusty so pardon the script kiddie like coding (and the email 
wrapping).

The solution might be:

replace 332 with:

if ( is_wp_error( $userid) ) {
    authLdap_debug('wp_insert_user result = ' . $userid->get_error_message());
    trigger_error( $userid->get_error_message() );
} else {
    authLdap_debug('user id = ' . $userid);
    // flag the user as an ldap user so we can hide the password
    // fields in the user profile
    update_user_meta($userid, 'authLDAP', true);

    // return a user object upon positive authorization
    return new WP_User( $userid);
}

**Comment by heiglandreas** [comment]
This should be "fixed" with #48. We can't add an error displaying directly at the login-screen but we added a log-entry into the authLDAP-debug log as well as into the error-log of the webserver
