### ISSUE TITLE
Does this work with phpLDAPAdmin

### ISSUE THREAD

**Issue by urinal-cake** [heiglandreas/authLdap#31]
Hi there,
I'm using phpLDAPAdmin to manage my LDAP. This plugin does not appear to have the ability to specify a host IP for use? We do not use account suffixes, and thus would be unable to connect using that method.

At the moment, we only use Host IP, Port, Base DN and our login attribute is uid.

**Comment by heiglandreas** [comment]
You can always use ```ldap://aaa.bbb.ccc.ddd:port``` as parameter for LDAP-URI. Therefore you can also use an IP-address. Or am I not getting something?

And I'm not really sure what you mean with "account suffixes". Can you give me an example? That would be great.

Generaly phpLdapAdmin is just an interface to your LDAP whereas authLdap is an authentication-connector between wordpress and your LDAP. So you should be able to add users to the LDAP via phpLDAPAdmin and use those users to login into wordpress via the authLdap-plugin.

**Comment by urinal-cake** [comment]
This plugin allows for the following information to be entered:

**"Simple" Page:**
Account Suffix
Base DN
Domain Controller(s)

**"Advanced" Page:**
LDAP Port

We do not use an account suffix. Instead, we point everything to our LDAP server (172.0.x.x) port 389, and refer to a base DN (in this case o=Puny Human)

How can we utilize this wordpress plugin if we cannot enter a host server to communicate with?

**Comment by urinal-cake** [comment]
I had two LDAP plugins installed, and any time I clicked on 'AuthLDAP' in settings, it was taking me to the options page for the other plugin. I've deactivated the other plugin and will attempt to configure with phpLDAPAdmin. My apologies for the mixup.

**Comment by heiglandreas** [comment]
Thanks for clarifying. I was just thinking I missed something completely as there is no "simple" or "advanced" page in the authLDAP-plugin-config :wink: 

Can I close this issue and when something strange happens you open a new one?

**Comment by heiglandreas** [comment]
BTW, which one was the other? I'd like to fix that you see the wrong config-page with the other plugin enabled

**Comment by urinal-cake** [comment]
Yeah, you can close it. I'm working on testing my configuration now, so if it doesn't work, I'll post back with a question.

The other plugin: https://wordpress.org/plugins/simple-ldap-login/

**Comment by heiglandreas** [comment]
Thanks! I'll dig into it why clicking onto the authLDAP-config-link brought you to the simple-ldap-login options page
