### ISSUE TITLE
LDAP-Extension

### ISSUE THREAD

**Issue by urinal-cake** [heiglandreas/authLdap#33]
I receive this message at the top of the AuthLDAP Settings page:
"The LDAP-Extension is not available on your WebServer. Therefore Everything you can alter here does not make any sense!"

I don't see where LDAP-Extension is a pre-requisite or requirement. Is something missing?

**Comment by heiglandreas** [comment]
Well, as you want to make an LDAP-connection you need the LDAP-module installed in PHP. You can control that using a file called ```info.php``` placed in wordpress main directory. Simply add

    <?php
    phpinfo();

as content to the file and then call this file from your webbrowser. It will display an informational page. On that page you should somewhere find information about the LDAP-module. If you can't find any you will have to install it. That mainly depends on the server-system you are using. And you might not be able to install it yourself on a shared environment. You will then need to contact your SysAdmin.

Without that extension NO ldap-plugin will work :cry:

**Comment by urinal-cake** [comment]
Fantastic, it's installed now and the error goes away. Still having troubles getting it working, but I'll sort that out and post other threads if necessary.

Does it state in the documentation anywhere that LDAP-Extension is a pre-requisite?

**Comment by heiglandreas** [comment]
Not sure to be honest. :smile:  I'll have a look and add it
