### ISSUE TITLE
Correct LDAP URI

### ISSUE THREAD

**Issue by urinal-cake** [heiglandreas/authLdap#34]
Hey Andreas,
I apologize for being such a burden to you, I feel like I am close to having this working.

Here are my settings.
**"Enable Authentication via LDAP?"** ON
**Debug AuthLDAP?** OFF
**Save entered passwords in thewordpress user table?** ON
**LDAP URI:** ldap://172.16.x.x:389
**Filter:** (uid=%s)
**Name Attribute:** givenname
**Second Name Attribute:** sn
**User-ID Attribute:** uid
**Mail Attribute:** mail
**Web-Attribute:** Web-Attribute
**Default Role:** Subscriber
**Use LDAP Groups to map to Roles?** OFF
**No Groups for Roles settings**
**No Role - group mapping settings**

When I attempt to login using a username that exists on a cn= object within phpLDAP, but does not yet exist on Wordpress, I am told Invalid Login.

Might you have any ideas or suggestions about how to address this, if any of the above configuration appears incorrect or if there is any logging?

**Comment by heiglandreas** [comment]
Can you give me more details on what the LDAP-entry looks like? Especially DN and UID would be of interest.

And the baseDN is missing from the LDAP-URI. It's the "path"-part of the uri. It normaly is the part of the DN without the UID=xyz. I can tell you in more detail when I know more about those LDAP-nodes

**Comment by urinal-cake** [comment]
Andreas,
Apologies if I appear a bit ignorant about this, but this is my first foray with LDAP outside of Active Directory.

By LDAP-Entry do you mean the LDAP URI as stated above? On another web-based application where we use LDAP, the Base DN is specified as "o=Puny Human" without double quotes. We have no LDAP filter set there, however. Our Login/User-ID attribute is uid.

I attempted to add more to the LDAP-URI, but without adding a user:password, so that it appears as "ldap://172.16.x.x:389/o=Puny Human" (without the x.x, for obvious obscurity reasons.) Oh wow! it works! I just tried it, it looks like all I needed to do is add the path to the end. Wow, thank you for your help! I guess you can disregard what I asked above.

I do have one final question. If I set the Default Role to Administrator so that all users that authenticate using LDAP have Administrator access, is there any security vulnerability there? The only people that have LDAP access are employees of our company, and they should have full access to this particular Wordpress.

**Comment by heiglandreas** [comment]
great to read that everything works :smiley:

The only security vulnersbility would be that administrators can do EVERYTHING in wordpress. But if that's what they should do - go ahead! That' a matter of wordpress where I'm not really that much a security expert. :wink:

Cheers

Andreas

-- 
Andreas Heigl
Andreas@heigl.org

**Comment by urinal-cake** [comment]
Hey Andreas,
One final note. I have 'Default Role' to 'Editor' and I'm finding that the following happens:
1) User, that does not have a user account, logs in.
2) User account is created with 'Editor' role
3) User logs out
4) Admin changes user's account role to 'Administrator'
5) User logs in
6) User's role gets automatically set back to 'Editor'

**Comment by heiglandreas** [comment]
Sorry for taking so much time to get back to you! 

Just to clarify that: You have set the default role to editor and you have also unchecked **Use LDAP Groups to map to Roles?**? That way you do NOT manage the users via LDAP.

Then you are right that it doesn't make sense to reset the role. @EmTeedee already has a patch for that which we are currently discussing. Won't take long.

**Comment by urinal-cake** [comment]
Hi Andreas,
Yes, "Use LDAP Groups to map to Roles?" is unchecked, and when set to Editor, any time somebody would login using their LDAP auth -- it would reset their permissions to Editor, even if they were already set to Administrator.

This was fine for those logging in for the first time, but others that need Administrative access kept getting their roles reset to Editor.

**Comment by heiglandreas** [comment]
Thanks for confirming this. I'll fix this then ASAP Expect a new version within the next 48 hours

**Comment by urinal-cake** [comment]
Great, thank you Andreas!

*Michael Sanders*
Studio Director, Puny Human <http://punyhumangames.com/> | +1 (919) 443-5110

**Comment by heiglandreas** [comment]
This issue should be fixed with the current master-branch from github. The release in the official wordpress-plugin-directory will follow soon!

**Comment by heiglandreas** [comment]
The official release is now also available. Should now work "out-of-the-box". If you have further issues feel free to open a new issue!

**Comment by urinal-cake** [comment]
Hi Andreas,
Apologies for the late response. I had a chance to test this with a coworker this morning, and it works great now, thank you!

**Comment by heiglandreas** [comment]
No Problem. Better a late response than no response :wink:
