### ISSUE TITLE
Allow DN in Group-Filter

### ISSUE THREAD

**Issue by deflomu** [heiglandreas/authLdap#4]
Hey,

it would be nice if you can add the Distinguished Name (DN) of a user as a variable to the Group-Filter field. This would be helpful because I use groupOfNames as groups and there the DN of a user is stored. Then it should be possible to set  "(&(objectClass=groupOfNames)(member=%dn))" as the group filter to get all the groups, where the user is a member of.

**Comment by ladrua** [comment]
could you add the ability to sett "uid" too? Since i changed Filter to be "(mail=%s)" ? Its nice to let users login with email address instead of uid...

**Comment by heiglandreas** [comment]
You should already be able to set the ```uid``` too. Or perhaps I'm missinterpreting your question. Could you explain more detailed what you want to do?

**Comment by ladrua** [comment]
If I use filter mail=%s, wont that make the group filter search the posixGroup memberUid with the mail address, rather then the uid?

**Comment by heiglandreas** [comment]
I think I get what you mean! Currently the value given in the login-window is used to check for groupMemberships when you use the ```%s```-string. But it should be the value from a configurable attribute from the LDAP-Server.

 Would you be so kind to open a new issue for that? Thanks!!!! :+1:
