### ISSUE TITLE
group-to-role assignment to follow hierarchy order

### ISSUE THREAD

**Issue by carmona** [heiglandreas/authLdap#40]
So i'm using group filter to allow only members of one group to login at all (e.g. group 4481) so they are assigned to the subscriber role in WP. But then, for my user account I need to be an administrator as well, so in my LDAP server I belong to groups 4481(website access) and 4494(website administrator).
However, the plugin gets the first group (4481) and sets me as a subscriber and ignores my right to be an administrator as I belong to group 4494, could this be fixed to grant a user his best access possible role available?

**Comment by heiglandreas** [comment]
This should be so, but it seems to be not working correctly.

I'll dig into it this weekend and try to provide a patch until monday!

**Comment by carmona** [comment]
Nice, thanks a lot! Now I'm having another problem with group filter querying: it only works on plugin version 1.3.0, as opposed to version 1.4.2, should I open another issue for that?

**Comment by heiglandreas** [comment]
Please open a new issue for that one and try to give as much info as possible **what** isn't workin in 1.4.2. Thanks!
