### ISSUE TITLE
Help with defining group attribute and filter

### ISSUE THREAD

**Issue by urinal-cake** [heiglandreas/authLdap#43]
Andreas,
I apologize in advance for how ignorant this must sound, but I have little to no experience dealing with LDAP groups, only their users.

We have 12 groups set up, all of them exist within ou=groups. For example, we have a group named cn=tools within ou=groups.
In phpLDAPAdmin, there doesn't seem to be a gidNumber for defining groups. I'm unsure if I should do anything to the Group-Filter.

Essentially, I'm just trying to map one group to Administrator, and ensure that anybody who isn't either can't auth or is a Subscriber.

**Comment by heiglandreas** [comment]
Sorry for comming back to you that late!

You can use ```cn``` as the **Group-Filter** and then just add f.i. ```tools``` to the **Adminstrator** section. Additionaly you set the **Default Role** to either ```Subscriber``` (everyone not in ```tools``` will be Subscriber) or ```none``` (everyone not in ```tools``` can't log in.

The **Group-Filter** depends on how your Users are mapped to the groups. The preset entry should be fine when you have a default OpenLDAP-setup. Otherwise I'd need to know more on how your users are mapped to the groups!

**Comment by urinal-cake** [comment]
Hey Andreas,
I tried adding cn= and cn as the group filter, and setting the administrator group mapping to galacide-svn, and was unable to login with a user that has not had an account generated. I used 'tools' as an example above, because it didn't seem to give anything away. I'm going to remove the below images once this is solved, but the actual group is galacide-svn. Here's a bit more information about how the LDAP is set up:

![image](https://cloud.githubusercontent.com/assets/7855304/6898470/7176fa42-d6c8-11e4-8a4f-ca48d892a569.png)
![image](https://cloud.githubusercontent.com/assets/7855304/6898499/94390192-d6c8-11e4-9fd7-1426ed7765d2.png)
![image](https://cloud.githubusercontent.com/assets/7855304/6898510/a325e2ec-d6c8-11e4-892d-d40dbf6fa462.png)

**Comment by heiglandreas** [comment]
Hi.
Thanks for the clarification.
You should try this:
**Group-Attribute:** cn (this will tell the plugin to match the values in the role-group-mapping fields agains the value that is stored in the ```cn```-Attribute)
**Group-Filter:** Either leave it at the default and if that doesn't work, change the ```%s``` to ```%dn%``` in that default. I'd need the actual attributes thart are stored in the ```galacide-svn```-group. You could find them using a tool like jxplorer which gives the raw data of the LDAP-Entries.

I hope that helps! If not, feel free to come back!

**Comment by urinal-cake** [comment]
Well, I'm poking around jxplorer now, trying to find the rawdata so that I
can get some more clues. Any idea what I should be looking for?

*Michael Sanders*
Studio Director, Puny Human <http://punyhumangames.com/> | +1 (919) 443-5110

**Comment by urinal-cake** [comment]
What I have been able to figure out is we use the groupOfUniqueNames
objectClass.
So this would mean our filter should look
like: (&(objectClass=groupOfUniqueNames)(memberUid=%s))

I'm learning so much! :)

**Comment by heiglandreas** [comment]
I've attached you an excerpt of our LDAP as seen through jXplore:
![bildschirmfoto 2015-03-30 um 17 21 38](https://cloud.githubusercontent.com/assets/91998/6899598/f371d13c-d701-11e4-84ac-cac5ab429740.png)
![bildschirmfoto 2015-03-30 um 17 21 04](https://cloud.githubusercontent.com/assets/91998/6899604/f72b8a0c-d701-11e4-9efc-a4538f31827f.png)

The user and the group are connected via the ```memberUid```- and the ```uniqueMember```-Attribute. Also each group has the objectClass ```posixGroup```. Therefore the filter to find the groups a user is member of is ```(&(objectclass=posixGroup)(memberUid=%s))``` where ```%s``` will  bve replaced by the users UID. Alternatively one could replace ```memberUid=%s``` with ```uniqueMember=%dn%``` where ```%dn%``` will the nbe replaced with the complete path to the user-node.

The entry ```cn``` could be used to map the WP-Roles to those LDAP-groups. But you can also use ```gitNumber``` (which in our case was easier)

Is that of any help?

**Comment by urinal-cake** [comment]
Yes, actually. That was a ton of help.
I had my filter set to: (&(objectClass=groupOfUniqueNames)(memberUid=%dn%))

However, until your last message, I did not think I could swap out memberUid for uniqueMember, which is what we use: Here is my filter now, that works: (&(objectClass=groupOfUniqueNames)(uniqueMember=%dn%))

![image](https://cloud.githubusercontent.com/assets/7855304/6899879/1ff9cd6c-d6d1-11e4-8637-8ab256fd6fb9.png)

**Comment by urinal-cake** [comment]
Thank you SO much Andreas. You have a ton of patience, and I appreciate it a lot.

**Comment by heiglandreas** [comment]
Great to hear that it now works! 

Have fun :smile:

**Comment by 8Cris1** [comment]
Hi, I'm sorry if I open this discussion again. I need to authenticate users through \'uid\'. The users are in a LDAP group in this form:

**cn** name-of-the-group

**member**:
uid=username1,ou=sub-group-name1,ou=group-name,dc=domain-name,dc=it
uid=username2,ou=sub-group-name2,ou=group-name,dc=domain-name,dc=it
uid=username3,ou=sub-group-name3,ou=group-name,dc=domain-name,dc=it

**objectClass**:
groupOfNames
top

I'm wondering which fields I have to compile in authLdap plugin and how considering the authentication is based on 'uid' and password. I'm a little bit confused. Than you.

**Comment by heiglandreas** [comment]
Hey @8Cris1: I've transfered your question to it's own issue #168
