### ISSUE TITLE
Save changes button not visible when map ldap groups is unchecked

### ISSUE THREAD

**Issue by chaplina** [heiglandreas/authLdap#44]
Likely has something to do with your javascript to hide the options.

**Comment by chaplina** [comment]
I guess I should say this I've tested this in Firefox and Chrome.

My desktop is Linux so testing in IE is not possible. :)

**Comment by chaplina** [comment]
I fixed it.
For view/admin.phtml:

 <?php endforeach; ?>
             </table>
         </fieldset>
+        </div>
         <fieldset class="buttons">
             <p class="submit">
                 <input type="submit" name="ldapOptionsSave" class="button button-primary" value="Save Changes" />
             </p>
         </fieldset>
-        </div>
     </form>
 </div>

**Comment by chaplina** [comment]
I fixed it but am unable to paste the diff in here.

Here's an image of the diff:

![shot-2015-03-28_11-07-36](https://cloud.githubusercontent.com/assets/11339046/6881562/ac9be7f2-d53a-11e4-9b7d-2a1e5c045ee8.jpg)

**Comment by chaplina** [comment]
Unfortunately, there is still an issue.

I can save changes now but the Map ldap groups option remains checked.

**Comment by chaplina** [comment]
Hmm...

It now seems to be working.

I had made the change while the plugin was active.

I removed the plugin, selected the Plugins page to deactivate it, re-added the plugin with the code change, activated it, and am now able to save the changes.

**Comment by heiglandreas** [comment]
I'm currently testing this one. I'll see that it is fixed in the next release!
