### ISSUE TITLE
feature request: bypass ldap auth for local WP user

### ISSUE THREAD

**Issue by chaplina** [heiglandreas/authLdap#45]
This is probably possible by checking the user's meta info for the authLDAP value.

This also changes the check for the admin account.

The proposed code in authLdap.php in function authLdap_login:

    authLdap_debug("User '$username' logging in");

    $login = get_user_by( 'login', '$username' );

    if ($login) {
	    if ($login->ID == 1) {
		    return $user;
	    }
	    $isauthLDAPuser = get_user_meta($login->ID,'authLDAP',true);
	    if (empty($isauthLDAPuser)) {
		    return $user;
            }
    }

//    if ($username == 'admin') {
//        authLdap_debug('Doing nothing for possible local user admin');
//        return $user;
//    }

**Comment by chaplina** [comment]
I've done some limited testing and it seems to work.  You may want to add some debug strings to verify.

**Comment by heiglandreas** [comment]
I'll have to do some furtehr testing on that one. Thanks for the code, I'll see what happens to it :wink:

**Comment by chaplina** [comment]
It seems that as of version 1.4.5 I can login with a local user without the code included above.

I'll look at the code and see how it handles a non-LDAP user.

**Comment by chaplina** [comment]
I was thinking about this request and am wondering if it might make more sense to add an option that would be an array of usernames and/or userids that would never use LDAP for authentication.

Example:

authLDAPLocalAuthOnly = ('admin',1,'wpadmin','fred','john');

You would then store the option as an array and compare the values at the spot in the login function where I inserted the code in the first post.

**Comment by chaplina** [comment]
FYI, my code was not working so do not use it. :)

**Comment by heiglandreas** [comment]
By now it should be possible to login with local users even though LDAP is enabled as long as no LDAP-User with the same username exists.

Therefore I'll close this issue.

Or did I miss something?

**Comment by chaplina** [comment]
Apologies again for not updating, local auth is working fine as long as there is no conflict.

The RFE to specify users who should never use LDAP for authentication is still valid I think but that can be placed in a separate issue.
