### ISSUE TITLE
authLdap_user_role not working in WP 4.1.1 multisite

### ISSUE THREAD

**Issue by chaplina** [heiglandreas/authLdap#49]
I replaced the code to get the role with:

```
$theuser = new WP_User( $uid );
$role = $theuser->roles[0];
```

It seems to be working but you will obviously want to test.

**Comment by chaplina** [comment]
I updated the title to indicate we are running multisite and the capabilities for each site are stored with the meta_key wp_blogid_capabilities.

I'll have to research my solution above regarding blogid, but I think it is set in the background and "passed" to the WP_User class.

**Comment by heiglandreas** [comment]
Can you give me a rough linenumber around where you did that change? That would be really great!

Thanks!

**Comment by chaplina** [comment]
I'm not near a computer but i can tell you it was just after the parameter validation (if (!uid)...) in the function.

On Apr 1, 2015 1:37 PM, Andreas Heigl <notifications@github.com> wrote:

Can you give me a rough linenumber around where you did that change? That would be really great!

Thanks!

**Comment by chaplina** [comment]
This seems to be working:

function authLdap_user_role($uid) {

    if (!$uid) {
        return '';
    }

    $user = new WP_User( $uid );
    if ( !empty( $user->roles ) && is_array( $user->roles ) ) {
       $role = $user->roles[0];
    }

    authLdap_debug("Existing user's role: {$role}");
    return $role;
}

**Comment by heiglandreas** [comment]
Thanks @chaplina! I'll give it a try during the easter-break and will be back on tuesday!

**Comment by Yeretho** [comment]
Would be interesting to know when multisite will be supported!

**Comment by heiglandreas** [comment]
There are some multisite-improvements available now…
