### ISSUE TITLE
Connexion troubles with LDAP Acls

### ISSUE THREAD

**Issue by kadogo** [heiglandreas/authLdap#55]
Hello,

I use Wordpress with your plugin and role mapping but when I try to use DSA and LDAP ACLs I have troubles.

Here the configuration I tried:
LDAP-URI:  ldaps://user-dsa:password-dsa@my-server.com/dc=base,dc=be

The debug give me this error:

<code>[Sun May 17 23:34:57.793243 2015] [:error] [pid 29360] [client IP:51239] [AuthLDAP] Group Filter: "(&(objectClass=organizationalRole)(roleOccupant=uid=user,ou=people,dc=base,dc=be))", referer: https://www.server.be/fr/wp-login.php</code>

<code>[Sun May 17 23:34:57.794458 2015] [:error] [pid 29360] [client IP:51239] [AuthLDAP] LDAP groups: [], referer: https://www.server.be/fr/wp-login.php</code>

<code>[Sun May 17 23:34:57.794508 2015] [:error] [pid 29360] [client IP:51239] [AuthLDAP] Role from LDAP group: , referer: https://www.server.be/fr/wp-login.php</code>

<code>[Sun May 17 23:34:57.794545 2015] [:error] [pid 29360] [client IP:51239] [AuthLDAP] role from group mapping: , referer: https://www.server.be/fr/wp-login.php</code>

<code>[Sun May 17 23:34:57.794569 2015] [:error] [pid 29360] [client IP:51239] [AuthLDAP] user is not in any group that is allowed access, referer: https://www.server.be/fr/wp-login.php</code>

When I tried a ldapsearch with my dsa user I grab the roles without problems.

Cheers.

**Comment by heiglandreas** [comment]
Sorry for not getting back earlier.

So when you do an ```ldapsearch -W -H "ldaps://user-dsa@my-server.com" -b dc=base,dc=be "(&(objectClass=organizationalRole)(roleOccupant=uid=user,ou=people,dc=base,dc=be))"``` you get the roles you are looking for?

**Comment by kadogo** [comment]
No problems ^^

Yes, I get the roles that my user have.

**Comment by kadogo** [comment]
I edit my previous comment beceause I had mis read your question.

**Comment by kadogo** [comment]
Hello back,
I think I have something.

Correct me if I'm false, but it is the user that try to catch the groups ?
I think it because it work if y open my acl for the roles branch to all.

It's not possible to bind with our user:password and than start the search of the ldap groups ?

**Comment by heiglandreas** [comment]
Hi @kadogo. Well, the user you are giving in the URI (so in your part the ```cn=wordpress,ou=dsa,dc=base,dc=be```) is the one used for the queries against the LDAP. But it might be possible that after the password has been checked that users login is used for further queries (which would be a bad idea actually) I have to check that before I can give you a definitive answer. I'll be back!

**Comment by kadogo** [comment]
I tried something, and it seem working.
Keep a look if it seem good for you.
https://github.com/heiglandreas/authLdap/pull/64
