### ISSUE TITLE
Display name publicly as

### ISSUE THREAD

**Issue by haderix** [heiglandreas/authLdap#61]
Everytime I login the profile option "Display name publicly as" is reset back to just my first name. I would like it to use my username instead. Is there a way to configure this?

**Comment by heiglandreas** [comment]
Hi @haderix. Sorry for getting back to you that late. The issue has by now been fixed. If you update to the latest version [1.4.9](https://github.com/heiglandreas/authLdap/releases/tag/v1.4.9) you should be fine.
