### ISSUE TITLE
Handle groups containing groups

### ISSUE THREAD

**Issue by maxCSA** [heiglandreas/authLdap#78]
The current filter is done on the GROUP entry, with a filter like (member=%dn%), so if the user is in a groupe inside the given group, it won't be matched as it should be.

One solution would be (for AD at least) to search the group provided in the configuration in the "memberOf" field on all groups, and then check the groups found in a recursive manner.

Just to illustrate my point, let's say we have a group called "ALL_USER" which contains the 2 groups "USER_DEPT_A" and "USER_DEPT_B". Currently we can't specify group "ALL_USER" because users are only defined in "USER_DEPT_A" and "USER_DEPT_B".

**Comment by heiglandreas** [comment]
I've just searched a bit and found http://stackoverflow.com/questions/12221288/how-to-get-the-nested-groups-in-ldap-ad which basically describes your case.

According to that site you should be able to find the grous the user is either a direct **or** an indirect member of by setting the group-filter to this:

    (member:1.2.840.113556.1.4.1941:=%dn%)

Sadly I don't have access to an AD so I can't test that one myself :frowning: 

Please get back with any results! Thanks

**Comment by maxCSA** [comment]
Hi,
Thanks a lot for this information, it's working like a charm. I wasn't aware of this feature with LDAP query. I might use it elsewhere as well!

So you can either close this request, or maybe add this information in the comment of the "Group-Filter" field.

Thanks again.
