### ISSUE TITLE
Check for already successfull authentication before "reauthenticating"

### ISSUE THREAD

**Issue by heiglandreas** [heiglandreas/authLdap#81]
This is an issue reported at https://wordpress.org/support/topic/authldap-doesnt-work-with-other-auth-plugins.

**Comment by litinoveweedle** [comment]
Hello heiglandreas,

sorry my mistake, I am use too much to PHP and WP, so steep learning curve for me.

I suggest better and simpler check based on WP_User object, this should do the trick:

<pre><code>
  function authLdap_login($user, $username, $password, $already_md5 = false)
  {
    // don't do anything when authLDAP is disabled
    if (! authLdap_get_option('Enabled')) {
        authLdap_debug('LDAP disabled in AuthLDAP plugin options (use the first option in the AuthLDAP options to enable it)');
        return $user;
    }

    if (isset($user) && $user->ID) {
        return $user;
    }

    authLdap_debug("User '$username' logging in");
</code></pre>

As for the rest of the answer why not provide configurable options of fallback? i.e. if user is already authenticated by previous hook would you *really* like to force http auth anyway?

Kind regards
Litin
