### ISSUE TITLE
RFE multisite option to restrict changes

### ISSUE THREAD

**Issue by chaplina** [heiglandreas/authLdap#82]
I'd like to see some options for restricting changes to the authLdap options in a multisite environment.

This will require a special settings page that is accessible in the Network Admin area.  Some plugins provide a settings link on the Plugin page.

Suggested options:
- hide Settings - authLdap for all but Super Admin (I've done this manually by modifying authLdap_addmenu and using is_super_admin in the if statement)
- allow Site Admins to make changes but Super Admin can lock down certain options (they are visible but grayed out via CSS)

Keep up the fantastic work!

**Comment by heiglandreas** [comment]
Thanks @chaplina. That's a good idea. 

As you already did you do some changes, would you mind adding them to this issue?

**Comment by chaplina** [comment]
My change was simple because I don't need the options mentioned as I want to hide the settings from all site admins:

```
function authLdap_addmenu()
{
    if (function_exists('add_options_page') && is_super_admin()) {
        add_options_page('AuthLDAP', 'AuthLDAP', 'manage_options', basename(__FILE__), 'authLdap_options_panel');
    }
}
```

**Comment by chaplina** [comment]
your new multisite setup feature should be adequate enough once it is completed
