### ISSUE TITLE
Fatal error: Cannot redeclare class LDAP

### ISSUE THREAD

**Issue by jscholtes** [heiglandreas/authLdap#91]
When i try to activate the Plugin i throws a fatal error:

Fatal error: Cannot redeclare class LDAP in /www/wpmu/wp-content/plugins/authldap/ldap.php on line 30

Any idea, where to search for a solution?

thx
juergen

**Comment by jscholtes** [comment]
Ok, seems to be a multisite-problem

**Comment by heiglandreas** [comment]
That should work on a multisite. Can you provide me a StackTrace? That would be great!
