### ISSUE TITLE
Example configuration

### ISSUE THREAD

**Issue by Yeretho** [heiglandreas/authLdap#92]
I'm currently configuring this plugin to connect with my LDAP environment but I'm having issues with the configuration. Is there an example configuration or detailed documentation that explains how to configure this plugin?

**Comment by heiglandreas** [comment]
Have you had a look at the [README](../)-file or http://andreas.heigl.org/2010/08/22/authldap/#more-4? 

If that isn't enough, feel free to describe your probems either here or via the [gitter-chat](https://gitter.im/heiglandreas/authLdap?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or via email to andreas AT heigl DOT org and I'll check what I can do.

**Comment by heiglandreas** [comment]
Hey @Yeretho - Anything I can do for you? I'll close this issue but when you have more questions feel free to reopen the issue.
