### ISSUE TITLE
Release version 1.4.10 on SVN does not match 1.4.10 on Github

### ISSUE THREAD

**Issue by wunc** [heiglandreas/authLdap#95]
Not sure what happened here, but version 1.4.10 that is available on the WordPress site is not the same code as version 1.4.10 here on Github. Compare the following files:

http://plugins.svn.wordpress.org/authldap/trunk/authLdap.php

https://github.com/heiglandreas/authLdap/blob/bc63c4ee422647bb79d57d18fae925299b814ec3/authLdap.php

They are different. (see line 37-38, for example)

**Comment by heiglandreas** [comment]
Oh damned!!

I can tell you what happened - SVN blew up the Git-repo :frowning: 

I thought I changed everything - Well obviously I've missed something…

For the 1.4.11-release (which will come soon) I've found a different way of keeping SVN and Git in sync. That will fix that.

**Comment by heiglandreas** [comment]
Hey @wunc - Now (#96) Github and Wordpress-Plugin have the same codebase. Automated deployment worked well.

Thanks for noting and mentioning!

**Comment by wunc** [comment]
Thanks, looks like its correct now!

**Comment by heiglandreas** [comment]
Not sure whether it's correct now, but it is at least equally incorrect on both sides :wink:

Thanks again for pointing out and bringing me to finally implement the automated build-tool.

Cheers

Andreas
