### ISSUE TITLE
deprecated function wp_setcookie()

### ISSUE THREAD

**Issue by wunc** [heiglandreas/authLdap#98]
> Notice:  wp_setcookie is <strong>deprecated</strong> since version 2.5! Use wp_set_auth_cookie() instead.

I'm not sure what this function (declared on line 515) is being used for, but I don't think it is being run at all. (I added an `error_log()` statement within  the function, and it doesn't show up at all in the log file.)

Therefore, for current versions of Wordpress, its probably safe to remove the function declaration completely, unless you really intended it to do something or wanted to maintain old old Wordpress compatibility. (2.5 was released in 2008) The plugin seems to be working well without it, though.

**Comment by heiglandreas** [comment]
Thanks for mentioning @wunc. 

As far as I can tell currently that function is not used ad all anymore. It's never called, just declared. But as it didn't do any harm it's never been removed.

I'm currently planning a complete refactoring of the plugin and that would be the point where it will be removed (or replaced by a decent implementation)

**Comment by saintberry** [comment]
@heiglandreas would it be possible to remove the function declaration and bump a minor version before you refactor?

We like to know what's going on in our dev env so log all errors and display on the frontend with `WP_DEBUG_DISPLAY`. 

We get quite a lot of noise with this deprecated notice on every request.

**Comment by heiglandreas** [comment]
Thanks for the hint! I'll do so as soon as possible (hopefully within this week!)
